// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: agynio/api/tracing/v1/tracing.proto

package tracingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TracingService_ListSpans_FullMethodName          = "/agynio.api.tracing.v1.TracingService/ListSpans"
	TracingService_GetSpan_FullMethodName            = "/agynio.api.tracing.v1.TracingService/GetSpan"
	TracingService_GetTrace_FullMethodName           = "/agynio.api.tracing.v1.TracingService/GetTrace"
	TracingService_GetTraceSummary_FullMethodName    = "/agynio.api.tracing.v1.TracingService/GetTraceSummary"
	TracingService_GetTraceSpanTotals_FullMethodName = "/agynio.api.tracing.v1.TracingService/GetTraceSpanTotals"
)

// TracingServiceClient is the client API for TracingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TracingService provides query access to span data ingested via the standard
// OTLP TraceService/Export endpoint. It supports paginated listing with
// filters, single-span lookup, and full-trace retrieval.
//
// All query responses use the standard OTel envelope hierarchy
// (ResourceSpans -> ScopeSpans -> Span) to preserve Resource and
// InstrumentationScope context alongside each span. This follows the same
// pattern used by Jaeger v3 QueryService.
type TracingServiceClient interface {
	// List spans matching the provided filters with pagination.
	// Each result span is wrapped in its ResourceSpans -> ScopeSpans envelope
	// so that Resource and InstrumentationScope context is preserved.
	ListSpans(ctx context.Context, in *ListSpansRequest, opts ...grpc.CallOption) (*ListSpansResponse, error)
	// Get a single span by trace_id and span_id, with its Resource and
	// InstrumentationScope context.
	GetSpan(ctx context.Context, in *GetSpanRequest, opts ...grpc.CallOption) (*GetSpanResponse, error)
	// Get all spans belonging to a trace, grouped by Resource and
	// InstrumentationScope.
	GetTrace(ctx context.Context, in *GetTraceRequest, opts ...grpc.CallOption) (*GetTraceResponse, error)
	// Get trace-level summary statistics.
	GetTraceSummary(ctx context.Context, in *GetTraceSummaryRequest, opts ...grpc.CallOption) (*GetTraceSummaryResponse, error)
	// Get span totals for a trace with optional filtering.
	GetTraceSpanTotals(ctx context.Context, in *GetTraceSpanTotalsRequest, opts ...grpc.CallOption) (*GetTraceSpanTotalsResponse, error)
}

type tracingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTracingServiceClient(cc grpc.ClientConnInterface) TracingServiceClient {
	return &tracingServiceClient{cc}
}

func (c *tracingServiceClient) ListSpans(ctx context.Context, in *ListSpansRequest, opts ...grpc.CallOption) (*ListSpansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpansResponse)
	err := c.cc.Invoke(ctx, TracingService_ListSpans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracingServiceClient) GetSpan(ctx context.Context, in *GetSpanRequest, opts ...grpc.CallOption) (*GetSpanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpanResponse)
	err := c.cc.Invoke(ctx, TracingService_GetSpan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracingServiceClient) GetTrace(ctx context.Context, in *GetTraceRequest, opts ...grpc.CallOption) (*GetTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTraceResponse)
	err := c.cc.Invoke(ctx, TracingService_GetTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracingServiceClient) GetTraceSummary(ctx context.Context, in *GetTraceSummaryRequest, opts ...grpc.CallOption) (*GetTraceSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTraceSummaryResponse)
	err := c.cc.Invoke(ctx, TracingService_GetTraceSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tracingServiceClient) GetTraceSpanTotals(ctx context.Context, in *GetTraceSpanTotalsRequest, opts ...grpc.CallOption) (*GetTraceSpanTotalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTraceSpanTotalsResponse)
	err := c.cc.Invoke(ctx, TracingService_GetTraceSpanTotals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TracingServiceServer is the server API for TracingService service.
// All implementations should embed UnimplementedTracingServiceServer
// for forward compatibility.
//
// TracingService provides query access to span data ingested via the standard
// OTLP TraceService/Export endpoint. It supports paginated listing with
// filters, single-span lookup, and full-trace retrieval.
//
// All query responses use the standard OTel envelope hierarchy
// (ResourceSpans -> ScopeSpans -> Span) to preserve Resource and
// InstrumentationScope context alongside each span. This follows the same
// pattern used by Jaeger v3 QueryService.
type TracingServiceServer interface {
	// List spans matching the provided filters with pagination.
	// Each result span is wrapped in its ResourceSpans -> ScopeSpans envelope
	// so that Resource and InstrumentationScope context is preserved.
	ListSpans(context.Context, *ListSpansRequest) (*ListSpansResponse, error)
	// Get a single span by trace_id and span_id, with its Resource and
	// InstrumentationScope context.
	GetSpan(context.Context, *GetSpanRequest) (*GetSpanResponse, error)
	// Get all spans belonging to a trace, grouped by Resource and
	// InstrumentationScope.
	GetTrace(context.Context, *GetTraceRequest) (*GetTraceResponse, error)
	// Get trace-level summary statistics.
	GetTraceSummary(context.Context, *GetTraceSummaryRequest) (*GetTraceSummaryResponse, error)
	// Get span totals for a trace with optional filtering.
	GetTraceSpanTotals(context.Context, *GetTraceSpanTotalsRequest) (*GetTraceSpanTotalsResponse, error)
}

// UnimplementedTracingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTracingServiceServer struct{}

func (UnimplementedTracingServiceServer) ListSpans(context.Context, *ListSpansRequest) (*ListSpansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpans not implemented")
}
func (UnimplementedTracingServiceServer) GetSpan(context.Context, *GetSpanRequest) (*GetSpanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpan not implemented")
}
func (UnimplementedTracingServiceServer) GetTrace(context.Context, *GetTraceRequest) (*GetTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrace not implemented")
}
func (UnimplementedTracingServiceServer) GetTraceSummary(context.Context, *GetTraceSummaryRequest) (*GetTraceSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraceSummary not implemented")
}
func (UnimplementedTracingServiceServer) GetTraceSpanTotals(context.Context, *GetTraceSpanTotalsRequest) (*GetTraceSpanTotalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraceSpanTotals not implemented")
}
func (UnimplementedTracingServiceServer) testEmbeddedByValue() {}

// UnsafeTracingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TracingServiceServer will
// result in compilation errors.
type UnsafeTracingServiceServer interface {
	mustEmbedUnimplementedTracingServiceServer()
}

func RegisterTracingServiceServer(s grpc.ServiceRegistrar, srv TracingServiceServer) {
	// If the following call panics, it indicates UnimplementedTracingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TracingService_ServiceDesc, srv)
}

func _TracingService_ListSpans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracingServiceServer).ListSpans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TracingService_ListSpans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracingServiceServer).ListSpans(ctx, req.(*ListSpansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracingService_GetSpan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracingServiceServer).GetSpan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TracingService_GetSpan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracingServiceServer).GetSpan(ctx, req.(*GetSpanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracingService_GetTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracingServiceServer).GetTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TracingService_GetTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracingServiceServer).GetTrace(ctx, req.(*GetTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracingService_GetTraceSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracingServiceServer).GetTraceSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TracingService_GetTraceSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracingServiceServer).GetTraceSummary(ctx, req.(*GetTraceSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TracingService_GetTraceSpanTotals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceSpanTotalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracingServiceServer).GetTraceSpanTotals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TracingService_GetTraceSpanTotals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracingServiceServer).GetTraceSpanTotals(ctx, req.(*GetTraceSpanTotalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TracingService_ServiceDesc is the grpc.ServiceDesc for TracingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TracingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.tracing.v1.TracingService",
	HandlerType: (*TracingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSpans",
			Handler:    _TracingService_ListSpans_Handler,
		},
		{
			MethodName: "GetSpan",
			Handler:    _TracingService_GetSpan_Handler,
		},
		{
			MethodName: "GetTrace",
			Handler:    _TracingService_GetTrace_Handler,
		},
		{
			MethodName: "GetTraceSummary",
			Handler:    _TracingService_GetTraceSummary_Handler,
		},
		{
			MethodName: "GetTraceSpanTotals",
			Handler:    _TracingService_GetTraceSpanTotals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/tracing/v1/tracing.proto",
}
