// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/tracing/v1/tracing.proto

package tracingv1

import (
	v1 "go.opentelemetry.io/proto/otlp/trace/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ordering for ListSpans results.
type ListSpansOrderBy int32

const (
	ListSpansOrderBy_LIST_SPANS_ORDER_BY_UNSPECIFIED     ListSpansOrderBy = 0
	ListSpansOrderBy_LIST_SPANS_ORDER_BY_START_TIME_DESC ListSpansOrderBy = 1
	ListSpansOrderBy_LIST_SPANS_ORDER_BY_START_TIME_ASC  ListSpansOrderBy = 2
)

// Enum value maps for ListSpansOrderBy.
var (
	ListSpansOrderBy_name = map[int32]string{
		0: "LIST_SPANS_ORDER_BY_UNSPECIFIED",
		1: "LIST_SPANS_ORDER_BY_START_TIME_DESC",
		2: "LIST_SPANS_ORDER_BY_START_TIME_ASC",
	}
	ListSpansOrderBy_value = map[string]int32{
		"LIST_SPANS_ORDER_BY_UNSPECIFIED":     0,
		"LIST_SPANS_ORDER_BY_START_TIME_DESC": 1,
		"LIST_SPANS_ORDER_BY_START_TIME_ASC":  2,
	}
)

func (x ListSpansOrderBy) Enum() *ListSpansOrderBy {
	p := new(ListSpansOrderBy)
	*p = x
	return p
}

func (x ListSpansOrderBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListSpansOrderBy) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_tracing_v1_tracing_proto_enumTypes[0].Descriptor()
}

func (ListSpansOrderBy) Type() protoreflect.EnumType {
	return &file_agynio_api_tracing_v1_tracing_proto_enumTypes[0]
}

func (x ListSpansOrderBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListSpansOrderBy.Descriptor instead.
func (ListSpansOrderBy) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{0}
}

// Derived status for a span, computed from OTel status_code + end_time.
type SpanStatus int32

const (
	SpanStatus_SPAN_STATUS_UNSPECIFIED SpanStatus = 0
	SpanStatus_SPAN_STATUS_RUNNING     SpanStatus = 1 // end_time = 0, status_code != ERROR
	SpanStatus_SPAN_STATUS_OK          SpanStatus = 2 // end_time > 0, status_code != ERROR
	SpanStatus_SPAN_STATUS_ERROR       SpanStatus = 3 // status_code = ERROR (regardless of end_time)
)

// Enum value maps for SpanStatus.
var (
	SpanStatus_name = map[int32]string{
		0: "SPAN_STATUS_UNSPECIFIED",
		1: "SPAN_STATUS_RUNNING",
		2: "SPAN_STATUS_OK",
		3: "SPAN_STATUS_ERROR",
	}
	SpanStatus_value = map[string]int32{
		"SPAN_STATUS_UNSPECIFIED": 0,
		"SPAN_STATUS_RUNNING":     1,
		"SPAN_STATUS_OK":          2,
		"SPAN_STATUS_ERROR":       3,
	}
)

func (x SpanStatus) Enum() *SpanStatus {
	p := new(SpanStatus)
	*p = x
	return p
}

func (x SpanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_tracing_v1_tracing_proto_enumTypes[1].Descriptor()
}

func (SpanStatus) Type() protoreflect.EnumType {
	return &file_agynio_api_tracing_v1_tracing_proto_enumTypes[1]
}

func (x SpanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpanStatus.Descriptor instead.
func (SpanStatus) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{1}
}

// Trace-level status derived from constituent span statuses.
type TraceStatus int32

const (
	TraceStatus_TRACE_STATUS_UNSPECIFIED TraceStatus = 0
	TraceStatus_TRACE_STATUS_RUNNING     TraceStatus = 1 // At least one span is RUNNING
	TraceStatus_TRACE_STATUS_COMPLETED   TraceStatus = 2 // All spans ended, none with ERROR
	TraceStatus_TRACE_STATUS_ERROR       TraceStatus = 3 // All spans ended, at least one ERROR
)

// Enum value maps for TraceStatus.
var (
	TraceStatus_name = map[int32]string{
		0: "TRACE_STATUS_UNSPECIFIED",
		1: "TRACE_STATUS_RUNNING",
		2: "TRACE_STATUS_COMPLETED",
		3: "TRACE_STATUS_ERROR",
	}
	TraceStatus_value = map[string]int32{
		"TRACE_STATUS_UNSPECIFIED": 0,
		"TRACE_STATUS_RUNNING":     1,
		"TRACE_STATUS_COMPLETED":   2,
		"TRACE_STATUS_ERROR":       3,
	}
)

func (x TraceStatus) Enum() *TraceStatus {
	p := new(TraceStatus)
	*p = x
	return p
}

func (x TraceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_tracing_v1_tracing_proto_enumTypes[2].Descriptor()
}

func (TraceStatus) Type() protoreflect.EnumType {
	return &file_agynio_api_tracing_v1_tracing_proto_enumTypes[2]
}

func (x TraceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceStatus.Descriptor instead.
func (TraceStatus) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{2}
}

// Filter criteria for ListSpans. All fields are optional and AND-combined.
type SpanFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                  // filter by trace (16 bytes)
	ParentSpanId  []byte                 `protobuf:"bytes,2,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`                 // filter by parent span (8 bytes)
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                       // filter by operation name (exact match)
	Kind          v1.Span_SpanKind       `protobuf:"varint,4,opt,name=kind,proto3,enum=opentelemetry.proto.trace.v1.Span_SpanKind" json:"kind,omitempty"`      // filter by span kind
	StartTimeMin  uint64                 `protobuf:"fixed64,5,opt,name=start_time_min,json=startTimeMin,proto3" json:"start_time_min,omitempty"`               // start time lower bound (inclusive, nanos)
	StartTimeMax  uint64                 `protobuf:"fixed64,6,opt,name=start_time_max,json=startTimeMax,proto3" json:"start_time_max,omitempty"`               // start time upper bound (inclusive, nanos)
	InProgress    *bool                  `protobuf:"varint,7,opt,name=in_progress,json=inProgress,proto3,oneof" json:"in_progress,omitempty"`                  // true = only in-progress, false = only completed, unset = both
	Names         []string               `protobuf:"bytes,8,rep,name=names,proto3" json:"names,omitempty"`                                                     // multiple span names, OR-combined (takes precedence over name)
	Statuses      []SpanStatus           `protobuf:"varint,9,rep,packed,name=statuses,proto3,enum=agynio.api.tracing.v1.SpanStatus" json:"statuses,omitempty"` // derived statuses, OR-combined (takes precedence over in_progress)
	MessageId     string                 `protobuf:"bytes,10,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                           // filter by message id (UUID, maps to resource attribute agyn.thread.message.id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanFilter) Reset() {
	*x = SpanFilter{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanFilter) ProtoMessage() {}

func (x *SpanFilter) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanFilter.ProtoReflect.Descriptor instead.
func (*SpanFilter) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{0}
}

func (x *SpanFilter) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *SpanFilter) GetParentSpanId() []byte {
	if x != nil {
		return x.ParentSpanId
	}
	return nil
}

func (x *SpanFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpanFilter) GetKind() v1.Span_SpanKind {
	if x != nil {
		return x.Kind
	}
	return v1.Span_SpanKind(0)
}

func (x *SpanFilter) GetStartTimeMin() uint64 {
	if x != nil {
		return x.StartTimeMin
	}
	return 0
}

func (x *SpanFilter) GetStartTimeMax() uint64 {
	if x != nil {
		return x.StartTimeMax
	}
	return 0
}

func (x *SpanFilter) GetInProgress() bool {
	if x != nil && x.InProgress != nil {
		return *x.InProgress
	}
	return false
}

func (x *SpanFilter) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *SpanFilter) GetStatuses() []SpanStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *SpanFilter) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ListSpansRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Filter         *SpanFilter            `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy        ListSpansOrderBy       `protobuf:"varint,4,opt,name=order_by,json=orderBy,proto3,enum=agynio.api.tracing.v1.ListSpansOrderBy" json:"order_by,omitempty"` // default: START_TIME_DESC
	OrganizationId string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`                         // required organization id (UUID)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSpansRequest) Reset() {
	*x = ListSpansRequest{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpansRequest) ProtoMessage() {}

func (x *ListSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpansRequest.ProtoReflect.Descriptor instead.
func (*ListSpansRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{1}
}

func (x *ListSpansRequest) GetFilter() *SpanFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListSpansRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSpansRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSpansRequest) GetOrderBy() ListSpansOrderBy {
	if x != nil {
		return x.OrderBy
	}
	return ListSpansOrderBy_LIST_SPANS_ORDER_BY_UNSPECIFIED
}

func (x *ListSpansRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListSpansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching spans in the standard OTel envelope hierarchy.
	// Spans sharing a Resource and InstrumentationScope are grouped under the
	// same ResourceSpans/ScopeSpans entry. The page_size limit applies to the
	// total number of Span messages across all ResourceSpans/ScopeSpans.
	ResourceSpans []*v1.ResourceSpans `protobuf:"bytes,1,rep,name=resource_spans,json=resourceSpans,proto3" json:"resource_spans,omitempty"`
	NextPageToken string              `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpansResponse) Reset() {
	*x = ListSpansResponse{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpansResponse) ProtoMessage() {}

func (x *ListSpansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpansResponse.ProtoReflect.Descriptor instead.
func (*ListSpansResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{2}
}

func (x *ListSpansResponse) GetResourceSpans() []*v1.ResourceSpans {
	if x != nil {
		return x.ResourceSpans
	}
	return nil
}

func (x *ListSpansResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetSpanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 16 bytes
	SpanId        []byte                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`    // 8 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpanRequest) Reset() {
	*x = GetSpanRequest{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpanRequest) ProtoMessage() {}

func (x *GetSpanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpanRequest.ProtoReflect.Descriptor instead.
func (*GetSpanRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{3}
}

func (x *GetSpanRequest) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *GetSpanRequest) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

type GetSpanResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The span wrapped in its ResourceSpans -> ScopeSpans envelope.
	// Contains exactly one ResourceSpans with one ScopeSpans with one Span.
	ResourceSpans []*v1.ResourceSpans `protobuf:"bytes,1,rep,name=resource_spans,json=resourceSpans,proto3" json:"resource_spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpanResponse) Reset() {
	*x = GetSpanResponse{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpanResponse) ProtoMessage() {}

func (x *GetSpanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpanResponse.ProtoReflect.Descriptor instead.
func (*GetSpanResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{4}
}

func (x *GetSpanResponse) GetResourceSpans() []*v1.ResourceSpans {
	if x != nil {
		return x.ResourceSpans
	}
	return nil
}

type GetTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceRequest) Reset() {
	*x = GetTraceRequest{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceRequest) ProtoMessage() {}

func (x *GetTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceRequest.ProtoReflect.Descriptor instead.
func (*GetTraceRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{5}
}

func (x *GetTraceRequest) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

type GetTraceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All spans in the trace, grouped by Resource and InstrumentationScope.
	// A trace spanning multiple services will have multiple ResourceSpans entries.
	ResourceSpans []*v1.ResourceSpans `protobuf:"bytes,1,rep,name=resource_spans,json=resourceSpans,proto3" json:"resource_spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceResponse) Reset() {
	*x = GetTraceResponse{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceResponse) ProtoMessage() {}

func (x *GetTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceResponse.ProtoReflect.Descriptor instead.
func (*GetTraceResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{6}
}

func (x *GetTraceResponse) GetResourceSpans() []*v1.ResourceSpans {
	if x != nil {
		return x.ResourceSpans
	}
	return nil
}

type GetTraceSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceSummaryRequest) Reset() {
	*x = GetTraceSummaryRequest{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceSummaryRequest) ProtoMessage() {}

func (x *GetTraceSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetTraceSummaryRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{7}
}

func (x *GetTraceSummaryRequest) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

type GetTraceSummaryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TraceId            []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Status             TraceStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=agynio.api.tracing.v1.TraceStatus" json:"status,omitempty"`
	FirstSpanStartTime uint64                 `protobuf:"fixed64,3,opt,name=first_span_start_time,json=firstSpanStartTime,proto3" json:"first_span_start_time,omitempty"`                                                            // earliest start_time_unix_nano
	LastSpanStartTime  uint64                 `protobuf:"fixed64,4,opt,name=last_span_start_time,json=lastSpanStartTime,proto3" json:"last_span_start_time,omitempty"`                                                               // latest start_time_unix_nano
	LastSpanEndTime    uint64                 `protobuf:"fixed64,5,opt,name=last_span_end_time,json=lastSpanEndTime,proto3" json:"last_span_end_time,omitempty"`                                                                     // latest end_time_unix_nano (0 if none completed)
	CountsByName       map[string]int64       `protobuf:"bytes,6,rep,name=counts_by_name,json=countsByName,proto3" json:"counts_by_name,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`       // key = span name, value = count
	CountsByStatus     map[string]int64       `protobuf:"bytes,7,rep,name=counts_by_status,json=countsByStatus,proto3" json:"counts_by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key = SpanStatus enum name, value = count
	TotalSpans         int64                  `protobuf:"varint,8,opt,name=total_spans,json=totalSpans,proto3" json:"total_spans,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTraceSummaryResponse) Reset() {
	*x = GetTraceSummaryResponse{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceSummaryResponse) ProtoMessage() {}

func (x *GetTraceSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetTraceSummaryResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{8}
}

func (x *GetTraceSummaryResponse) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *GetTraceSummaryResponse) GetStatus() TraceStatus {
	if x != nil {
		return x.Status
	}
	return TraceStatus_TRACE_STATUS_UNSPECIFIED
}

func (x *GetTraceSummaryResponse) GetFirstSpanStartTime() uint64 {
	if x != nil {
		return x.FirstSpanStartTime
	}
	return 0
}

func (x *GetTraceSummaryResponse) GetLastSpanStartTime() uint64 {
	if x != nil {
		return x.LastSpanStartTime
	}
	return 0
}

func (x *GetTraceSummaryResponse) GetLastSpanEndTime() uint64 {
	if x != nil {
		return x.LastSpanEndTime
	}
	return 0
}

func (x *GetTraceSummaryResponse) GetCountsByName() map[string]int64 {
	if x != nil {
		return x.CountsByName
	}
	return nil
}

func (x *GetTraceSummaryResponse) GetCountsByStatus() map[string]int64 {
	if x != nil {
		return x.CountsByStatus
	}
	return nil
}

func (x *GetTraceSummaryResponse) GetTotalSpans() int64 {
	if x != nil {
		return x.TotalSpans
	}
	return 0
}

type GetTraceSpanTotalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                  // 16 bytes
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`                                                     // span names to include (empty = all)
	Statuses      []SpanStatus           `protobuf:"varint,3,rep,packed,name=statuses,proto3,enum=agynio.api.tracing.v1.SpanStatus" json:"statuses,omitempty"` // derived statuses to include (empty = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceSpanTotalsRequest) Reset() {
	*x = GetTraceSpanTotalsRequest{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceSpanTotalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceSpanTotalsRequest) ProtoMessage() {}

func (x *GetTraceSpanTotalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceSpanTotalsRequest.ProtoReflect.Descriptor instead.
func (*GetTraceSpanTotalsRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{9}
}

func (x *GetTraceSpanTotalsRequest) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *GetTraceSpanTotalsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *GetTraceSpanTotalsRequest) GetStatuses() []SpanStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type GetTraceSpanTotalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpanCount     int64                  `protobuf:"varint,1,opt,name=span_count,json=spanCount,proto3" json:"span_count,omitempty"`
	TokenUsage    *TokenUsageTotals      `protobuf:"bytes,2,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceSpanTotalsResponse) Reset() {
	*x = GetTraceSpanTotalsResponse{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceSpanTotalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceSpanTotalsResponse) ProtoMessage() {}

func (x *GetTraceSpanTotalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceSpanTotalsResponse.ProtoReflect.Descriptor instead.
func (*GetTraceSpanTotalsResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{10}
}

func (x *GetTraceSpanTotalsResponse) GetSpanCount() int64 {
	if x != nil {
		return x.SpanCount
	}
	return 0
}

func (x *GetTraceSpanTotalsResponse) GetTokenUsage() *TokenUsageTotals {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

type TokenUsageTotals struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InputTokens          int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens         int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheReadInputTokens int64                  `protobuf:"varint,3,opt,name=cache_read_input_tokens,json=cacheReadInputTokens,proto3" json:"cache_read_input_tokens,omitempty"`
	ReasoningTokens      int64                  `protobuf:"varint,4,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	TotalTokens          int64                  `protobuf:"varint,5,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"` // server-computed: input + output
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TokenUsageTotals) Reset() {
	*x = TokenUsageTotals{}
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsageTotals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsageTotals) ProtoMessage() {}

func (x *TokenUsageTotals) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_tracing_v1_tracing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsageTotals.ProtoReflect.Descriptor instead.
func (*TokenUsageTotals) Descriptor() ([]byte, []int) {
	return file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP(), []int{11}
}

func (x *TokenUsageTotals) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsageTotals) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsageTotals) GetCacheReadInputTokens() int64 {
	if x != nil {
		return x.CacheReadInputTokens
	}
	return 0
}

func (x *TokenUsageTotals) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *TokenUsageTotals) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

var File_agynio_api_tracing_v1_tracing_proto protoreflect.FileDescriptor

const file_agynio_api_tracing_v1_tracing_proto_rawDesc = "" +
	"\n" +
	"#agynio/api/tracing/v1/tracing.proto\x12\x15agynio.api.tracing.v1\x1a(opentelemetry/proto/trace/v1/trace.proto\"\x98\x03\n" +
	"\n" +
	"SpanFilter\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12$\n" +
	"\x0eparent_span_id\x18\x02 \x01(\fR\fparentSpanId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12?\n" +
	"\x04kind\x18\x04 \x01(\x0e2+.opentelemetry.proto.trace.v1.Span.SpanKindR\x04kind\x12$\n" +
	"\x0estart_time_min\x18\x05 \x01(\x06R\fstartTimeMin\x12$\n" +
	"\x0estart_time_max\x18\x06 \x01(\x06R\fstartTimeMax\x12$\n" +
	"\vin_progress\x18\a \x01(\bH\x00R\n" +
	"inProgress\x88\x01\x01\x12\x14\n" +
	"\x05names\x18\b \x03(\tR\x05names\x12=\n" +
	"\bstatuses\x18\t \x03(\x0e2!.agynio.api.tracing.v1.SpanStatusR\bstatuses\x12\x1d\n" +
	"\n" +
	"message_id\x18\n" +
	" \x01(\tR\tmessageIdB\x0e\n" +
	"\f_in_progress\"\xf6\x01\n" +
	"\x10ListSpansRequest\x129\n" +
	"\x06filter\x18\x01 \x01(\v2!.agynio.api.tracing.v1.SpanFilterR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12B\n" +
	"\border_by\x18\x04 \x01(\x0e2'.agynio.api.tracing.v1.ListSpansOrderByR\aorderBy\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\"\x8f\x01\n" +
	"\x11ListSpansResponse\x12R\n" +
	"\x0eresource_spans\x18\x01 \x03(\v2+.opentelemetry.proto.trace.v1.ResourceSpansR\rresourceSpans\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"D\n" +
	"\x0eGetSpanRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\fR\x06spanId\"e\n" +
	"\x0fGetSpanResponse\x12R\n" +
	"\x0eresource_spans\x18\x01 \x03(\v2+.opentelemetry.proto.trace.v1.ResourceSpansR\rresourceSpans\",\n" +
	"\x0fGetTraceRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\"f\n" +
	"\x10GetTraceResponse\x12R\n" +
	"\x0eresource_spans\x18\x01 \x03(\v2+.opentelemetry.proto.trace.v1.ResourceSpansR\rresourceSpans\"3\n" +
	"\x16GetTraceSummaryRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\"\xfc\x04\n" +
	"\x17GetTraceSummaryResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".agynio.api.tracing.v1.TraceStatusR\x06status\x121\n" +
	"\x15first_span_start_time\x18\x03 \x01(\x06R\x12firstSpanStartTime\x12/\n" +
	"\x14last_span_start_time\x18\x04 \x01(\x06R\x11lastSpanStartTime\x12+\n" +
	"\x12last_span_end_time\x18\x05 \x01(\x06R\x0flastSpanEndTime\x12f\n" +
	"\x0ecounts_by_name\x18\x06 \x03(\v2@.agynio.api.tracing.v1.GetTraceSummaryResponse.CountsByNameEntryR\fcountsByName\x12l\n" +
	"\x10counts_by_status\x18\a \x03(\v2B.agynio.api.tracing.v1.GetTraceSummaryResponse.CountsByStatusEntryR\x0ecountsByStatus\x12\x1f\n" +
	"\vtotal_spans\x18\b \x01(\x03R\n" +
	"totalSpans\x1a?\n" +
	"\x11CountsByNameEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aA\n" +
	"\x13CountsByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x8b\x01\n" +
	"\x19GetTraceSpanTotalsRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12=\n" +
	"\bstatuses\x18\x03 \x03(\x0e2!.agynio.api.tracing.v1.SpanStatusR\bstatuses\"\x85\x01\n" +
	"\x1aGetTraceSpanTotalsResponse\x12\x1d\n" +
	"\n" +
	"span_count\x18\x01 \x01(\x03R\tspanCount\x12H\n" +
	"\vtoken_usage\x18\x02 \x01(\v2'.agynio.api.tracing.v1.TokenUsageTotalsR\n" +
	"tokenUsage\"\xdf\x01\n" +
	"\x10TokenUsageTotals\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x125\n" +
	"\x17cache_read_input_tokens\x18\x03 \x01(\x03R\x14cacheReadInputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x04 \x01(\x03R\x0freasoningTokens\x12!\n" +
	"\ftotal_tokens\x18\x05 \x01(\x03R\vtotalTokens*\x88\x01\n" +
	"\x10ListSpansOrderBy\x12#\n" +
	"\x1fLIST_SPANS_ORDER_BY_UNSPECIFIED\x10\x00\x12'\n" +
	"#LIST_SPANS_ORDER_BY_START_TIME_DESC\x10\x01\x12&\n" +
	"\"LIST_SPANS_ORDER_BY_START_TIME_ASC\x10\x02*m\n" +
	"\n" +
	"SpanStatus\x12\x1b\n" +
	"\x17SPAN_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SPAN_STATUS_RUNNING\x10\x01\x12\x12\n" +
	"\x0eSPAN_STATUS_OK\x10\x02\x12\x15\n" +
	"\x11SPAN_STATUS_ERROR\x10\x03*y\n" +
	"\vTraceStatus\x12\x1c\n" +
	"\x18TRACE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRACE_STATUS_RUNNING\x10\x01\x12\x1a\n" +
	"\x16TRACE_STATUS_COMPLETED\x10\x02\x12\x16\n" +
	"\x12TRACE_STATUS_ERROR\x10\x032\x94\x04\n" +
	"\x0eTracingService\x12^\n" +
	"\tListSpans\x12'.agynio.api.tracing.v1.ListSpansRequest\x1a(.agynio.api.tracing.v1.ListSpansResponse\x12X\n" +
	"\aGetSpan\x12%.agynio.api.tracing.v1.GetSpanRequest\x1a&.agynio.api.tracing.v1.GetSpanResponse\x12[\n" +
	"\bGetTrace\x12&.agynio.api.tracing.v1.GetTraceRequest\x1a'.agynio.api.tracing.v1.GetTraceResponse\x12p\n" +
	"\x0fGetTraceSummary\x12-.agynio.api.tracing.v1.GetTraceSummaryRequest\x1a..agynio.api.tracing.v1.GetTraceSummaryResponse\x12y\n" +
	"\x12GetTraceSpanTotals\x120.agynio.api.tracing.v1.GetTraceSpanTotalsRequest\x1a1.agynio.api.tracing.v1.GetTraceSpanTotalsResponseB;Z9github.com/agynio/api/gen/agynio/api/tracing/v1;tracingv1b\x06proto3"

var (
	file_agynio_api_tracing_v1_tracing_proto_rawDescOnce sync.Once
	file_agynio_api_tracing_v1_tracing_proto_rawDescData []byte
)

func file_agynio_api_tracing_v1_tracing_proto_rawDescGZIP() []byte {
	file_agynio_api_tracing_v1_tracing_proto_rawDescOnce.Do(func() {
		file_agynio_api_tracing_v1_tracing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_tracing_v1_tracing_proto_rawDesc), len(file_agynio_api_tracing_v1_tracing_proto_rawDesc)))
	})
	return file_agynio_api_tracing_v1_tracing_proto_rawDescData
}

var file_agynio_api_tracing_v1_tracing_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agynio_api_tracing_v1_tracing_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agynio_api_tracing_v1_tracing_proto_goTypes = []any{
	(ListSpansOrderBy)(0),              // 0: agynio.api.tracing.v1.ListSpansOrderBy
	(SpanStatus)(0),                    // 1: agynio.api.tracing.v1.SpanStatus
	(TraceStatus)(0),                   // 2: agynio.api.tracing.v1.TraceStatus
	(*SpanFilter)(nil),                 // 3: agynio.api.tracing.v1.SpanFilter
	(*ListSpansRequest)(nil),           // 4: agynio.api.tracing.v1.ListSpansRequest
	(*ListSpansResponse)(nil),          // 5: agynio.api.tracing.v1.ListSpansResponse
	(*GetSpanRequest)(nil),             // 6: agynio.api.tracing.v1.GetSpanRequest
	(*GetSpanResponse)(nil),            // 7: agynio.api.tracing.v1.GetSpanResponse
	(*GetTraceRequest)(nil),            // 8: agynio.api.tracing.v1.GetTraceRequest
	(*GetTraceResponse)(nil),           // 9: agynio.api.tracing.v1.GetTraceResponse
	(*GetTraceSummaryRequest)(nil),     // 10: agynio.api.tracing.v1.GetTraceSummaryRequest
	(*GetTraceSummaryResponse)(nil),    // 11: agynio.api.tracing.v1.GetTraceSummaryResponse
	(*GetTraceSpanTotalsRequest)(nil),  // 12: agynio.api.tracing.v1.GetTraceSpanTotalsRequest
	(*GetTraceSpanTotalsResponse)(nil), // 13: agynio.api.tracing.v1.GetTraceSpanTotalsResponse
	(*TokenUsageTotals)(nil),           // 14: agynio.api.tracing.v1.TokenUsageTotals
	nil,                                // 15: agynio.api.tracing.v1.GetTraceSummaryResponse.CountsByNameEntry
	nil,                                // 16: agynio.api.tracing.v1.GetTraceSummaryResponse.CountsByStatusEntry
	(v1.Span_SpanKind)(0),              // 17: opentelemetry.proto.trace.v1.Span.SpanKind
	(*v1.ResourceSpans)(nil),           // 18: opentelemetry.proto.trace.v1.ResourceSpans
}
var file_agynio_api_tracing_v1_tracing_proto_depIdxs = []int32{
	17, // 0: agynio.api.tracing.v1.SpanFilter.kind:type_name -> opentelemetry.proto.trace.v1.Span.SpanKind
	1,  // 1: agynio.api.tracing.v1.SpanFilter.statuses:type_name -> agynio.api.tracing.v1.SpanStatus
	3,  // 2: agynio.api.tracing.v1.ListSpansRequest.filter:type_name -> agynio.api.tracing.v1.SpanFilter
	0,  // 3: agynio.api.tracing.v1.ListSpansRequest.order_by:type_name -> agynio.api.tracing.v1.ListSpansOrderBy
	18, // 4: agynio.api.tracing.v1.ListSpansResponse.resource_spans:type_name -> opentelemetry.proto.trace.v1.ResourceSpans
	18, // 5: agynio.api.tracing.v1.GetSpanResponse.resource_spans:type_name -> opentelemetry.proto.trace.v1.ResourceSpans
	18, // 6: agynio.api.tracing.v1.GetTraceResponse.resource_spans:type_name -> opentelemetry.proto.trace.v1.ResourceSpans
	2,  // 7: agynio.api.tracing.v1.GetTraceSummaryResponse.status:type_name -> agynio.api.tracing.v1.TraceStatus
	15, // 8: agynio.api.tracing.v1.GetTraceSummaryResponse.counts_by_name:type_name -> agynio.api.tracing.v1.GetTraceSummaryResponse.CountsByNameEntry
	16, // 9: agynio.api.tracing.v1.GetTraceSummaryResponse.counts_by_status:type_name -> agynio.api.tracing.v1.GetTraceSummaryResponse.CountsByStatusEntry
	1,  // 10: agynio.api.tracing.v1.GetTraceSpanTotalsRequest.statuses:type_name -> agynio.api.tracing.v1.SpanStatus
	14, // 11: agynio.api.tracing.v1.GetTraceSpanTotalsResponse.token_usage:type_name -> agynio.api.tracing.v1.TokenUsageTotals
	4,  // 12: agynio.api.tracing.v1.TracingService.ListSpans:input_type -> agynio.api.tracing.v1.ListSpansRequest
	6,  // 13: agynio.api.tracing.v1.TracingService.GetSpan:input_type -> agynio.api.tracing.v1.GetSpanRequest
	8,  // 14: agynio.api.tracing.v1.TracingService.GetTrace:input_type -> agynio.api.tracing.v1.GetTraceRequest
	10, // 15: agynio.api.tracing.v1.TracingService.GetTraceSummary:input_type -> agynio.api.tracing.v1.GetTraceSummaryRequest
	12, // 16: agynio.api.tracing.v1.TracingService.GetTraceSpanTotals:input_type -> agynio.api.tracing.v1.GetTraceSpanTotalsRequest
	5,  // 17: agynio.api.tracing.v1.TracingService.ListSpans:output_type -> agynio.api.tracing.v1.ListSpansResponse
	7,  // 18: agynio.api.tracing.v1.TracingService.GetSpan:output_type -> agynio.api.tracing.v1.GetSpanResponse
	9,  // 19: agynio.api.tracing.v1.TracingService.GetTrace:output_type -> agynio.api.tracing.v1.GetTraceResponse
	11, // 20: agynio.api.tracing.v1.TracingService.GetTraceSummary:output_type -> agynio.api.tracing.v1.GetTraceSummaryResponse
	13, // 21: agynio.api.tracing.v1.TracingService.GetTraceSpanTotals:output_type -> agynio.api.tracing.v1.GetTraceSpanTotalsResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_agynio_api_tracing_v1_tracing_proto_init() }
func file_agynio_api_tracing_v1_tracing_proto_init() {
	if File_agynio_api_tracing_v1_tracing_proto != nil {
		return
	}
	file_agynio_api_tracing_v1_tracing_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_tracing_v1_tracing_proto_rawDesc), len(file_agynio_api_tracing_v1_tracing_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_tracing_v1_tracing_proto_goTypes,
		DependencyIndexes: file_agynio_api_tracing_v1_tracing_proto_depIdxs,
		EnumInfos:         file_agynio_api_tracing_v1_tracing_proto_enumTypes,
		MessageInfos:      file_agynio_api_tracing_v1_tracing_proto_msgTypes,
	}.Build()
	File_agynio_api_tracing_v1_tracing_proto = out.File
	file_agynio_api_tracing_v1_tracing_proto_goTypes = nil
	file_agynio_api_tracing_v1_tracing_proto_depIdxs = nil
}
