// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: agynio/api/agents/v1/agents.proto

package agentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentsService_CreateAgent_FullMethodName                     = "/agynio.api.agents.v1.AgentsService/CreateAgent"
	AgentsService_GetAgent_FullMethodName                        = "/agynio.api.agents.v1.AgentsService/GetAgent"
	AgentsService_ResolveAgentIdentity_FullMethodName            = "/agynio.api.agents.v1.AgentsService/ResolveAgentIdentity"
	AgentsService_UpdateAgent_FullMethodName                     = "/agynio.api.agents.v1.AgentsService/UpdateAgent"
	AgentsService_DeleteAgent_FullMethodName                     = "/agynio.api.agents.v1.AgentsService/DeleteAgent"
	AgentsService_ListAgents_FullMethodName                      = "/agynio.api.agents.v1.AgentsService/ListAgents"
	AgentsService_SetAgentRole_FullMethodName                    = "/agynio.api.agents.v1.AgentsService/SetAgentRole"
	AgentsService_RemoveAgentRole_FullMethodName                 = "/agynio.api.agents.v1.AgentsService/RemoveAgentRole"
	AgentsService_ListAgentRoles_FullMethodName                  = "/agynio.api.agents.v1.AgentsService/ListAgentRoles"
	AgentsService_ListMyAgentRoles_FullMethodName                = "/agynio.api.agents.v1.AgentsService/ListMyAgentRoles"
	AgentsService_CreateVolume_FullMethodName                    = "/agynio.api.agents.v1.AgentsService/CreateVolume"
	AgentsService_GetVolume_FullMethodName                       = "/agynio.api.agents.v1.AgentsService/GetVolume"
	AgentsService_UpdateVolume_FullMethodName                    = "/agynio.api.agents.v1.AgentsService/UpdateVolume"
	AgentsService_DeleteVolume_FullMethodName                    = "/agynio.api.agents.v1.AgentsService/DeleteVolume"
	AgentsService_ListVolumes_FullMethodName                     = "/agynio.api.agents.v1.AgentsService/ListVolumes"
	AgentsService_CreateVolumeAttachment_FullMethodName          = "/agynio.api.agents.v1.AgentsService/CreateVolumeAttachment"
	AgentsService_GetVolumeAttachment_FullMethodName             = "/agynio.api.agents.v1.AgentsService/GetVolumeAttachment"
	AgentsService_DeleteVolumeAttachment_FullMethodName          = "/agynio.api.agents.v1.AgentsService/DeleteVolumeAttachment"
	AgentsService_ListVolumeAttachments_FullMethodName           = "/agynio.api.agents.v1.AgentsService/ListVolumeAttachments"
	AgentsService_CreateMcp_FullMethodName                       = "/agynio.api.agents.v1.AgentsService/CreateMcp"
	AgentsService_GetMcp_FullMethodName                          = "/agynio.api.agents.v1.AgentsService/GetMcp"
	AgentsService_UpdateMcp_FullMethodName                       = "/agynio.api.agents.v1.AgentsService/UpdateMcp"
	AgentsService_DeleteMcp_FullMethodName                       = "/agynio.api.agents.v1.AgentsService/DeleteMcp"
	AgentsService_ListMcps_FullMethodName                        = "/agynio.api.agents.v1.AgentsService/ListMcps"
	AgentsService_CreateSkill_FullMethodName                     = "/agynio.api.agents.v1.AgentsService/CreateSkill"
	AgentsService_GetSkill_FullMethodName                        = "/agynio.api.agents.v1.AgentsService/GetSkill"
	AgentsService_UpdateSkill_FullMethodName                     = "/agynio.api.agents.v1.AgentsService/UpdateSkill"
	AgentsService_DeleteSkill_FullMethodName                     = "/agynio.api.agents.v1.AgentsService/DeleteSkill"
	AgentsService_ListSkills_FullMethodName                      = "/agynio.api.agents.v1.AgentsService/ListSkills"
	AgentsService_CreateHook_FullMethodName                      = "/agynio.api.agents.v1.AgentsService/CreateHook"
	AgentsService_GetHook_FullMethodName                         = "/agynio.api.agents.v1.AgentsService/GetHook"
	AgentsService_UpdateHook_FullMethodName                      = "/agynio.api.agents.v1.AgentsService/UpdateHook"
	AgentsService_DeleteHook_FullMethodName                      = "/agynio.api.agents.v1.AgentsService/DeleteHook"
	AgentsService_ListHooks_FullMethodName                       = "/agynio.api.agents.v1.AgentsService/ListHooks"
	AgentsService_CreateEnv_FullMethodName                       = "/agynio.api.agents.v1.AgentsService/CreateEnv"
	AgentsService_GetEnv_FullMethodName                          = "/agynio.api.agents.v1.AgentsService/GetEnv"
	AgentsService_UpdateEnv_FullMethodName                       = "/agynio.api.agents.v1.AgentsService/UpdateEnv"
	AgentsService_DeleteEnv_FullMethodName                       = "/agynio.api.agents.v1.AgentsService/DeleteEnv"
	AgentsService_ListEnvs_FullMethodName                        = "/agynio.api.agents.v1.AgentsService/ListEnvs"
	AgentsService_CreateInitScript_FullMethodName                = "/agynio.api.agents.v1.AgentsService/CreateInitScript"
	AgentsService_GetInitScript_FullMethodName                   = "/agynio.api.agents.v1.AgentsService/GetInitScript"
	AgentsService_UpdateInitScript_FullMethodName                = "/agynio.api.agents.v1.AgentsService/UpdateInitScript"
	AgentsService_DeleteInitScript_FullMethodName                = "/agynio.api.agents.v1.AgentsService/DeleteInitScript"
	AgentsService_ListInitScripts_FullMethodName                 = "/agynio.api.agents.v1.AgentsService/ListInitScripts"
	AgentsService_CreateImagePullSecretAttachment_FullMethodName = "/agynio.api.agents.v1.AgentsService/CreateImagePullSecretAttachment"
	AgentsService_GetImagePullSecretAttachment_FullMethodName    = "/agynio.api.agents.v1.AgentsService/GetImagePullSecretAttachment"
	AgentsService_DeleteImagePullSecretAttachment_FullMethodName = "/agynio.api.agents.v1.AgentsService/DeleteImagePullSecretAttachment"
	AgentsService_ListImagePullSecretAttachments_FullMethodName  = "/agynio.api.agents.v1.AgentsService/ListImagePullSecretAttachments"
)

// AgentsServiceClient is the client API for AgentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentsService manages agent resources: agents, volumes, volume attachments,
// MCP servers, skills, hooks, environment variables, and init scripts.
//
// This is a control-plane service. It stores desired state;
// other services reconcile toward it.
type AgentsServiceClient interface {
	// --- Agents ---
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error)
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error)
	// Resolve an agent and organization by identity ID.
	ResolveAgentIdentity(ctx context.Context, in *ResolveAgentIdentityRequest, opts ...grpc.CallOption) (*ResolveAgentIdentityResponse, error)
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error)
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	SetAgentRole(ctx context.Context, in *SetAgentRoleRequest, opts ...grpc.CallOption) (*SetAgentRoleResponse, error)
	RemoveAgentRole(ctx context.Context, in *RemoveAgentRoleRequest, opts ...grpc.CallOption) (*RemoveAgentRoleResponse, error)
	ListAgentRoles(ctx context.Context, in *ListAgentRolesRequest, opts ...grpc.CallOption) (*ListAgentRolesResponse, error)
	ListMyAgentRoles(ctx context.Context, in *ListMyAgentRolesRequest, opts ...grpc.CallOption) (*ListMyAgentRolesResponse, error)
	// --- Volumes ---
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error)
	UpdateVolume(ctx context.Context, in *UpdateVolumeRequest, opts ...grpc.CallOption) (*UpdateVolumeResponse, error)
	DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	// --- Volume Attachments (no Update) ---
	CreateVolumeAttachment(ctx context.Context, in *CreateVolumeAttachmentRequest, opts ...grpc.CallOption) (*CreateVolumeAttachmentResponse, error)
	GetVolumeAttachment(ctx context.Context, in *GetVolumeAttachmentRequest, opts ...grpc.CallOption) (*GetVolumeAttachmentResponse, error)
	DeleteVolumeAttachment(ctx context.Context, in *DeleteVolumeAttachmentRequest, opts ...grpc.CallOption) (*DeleteVolumeAttachmentResponse, error)
	ListVolumeAttachments(ctx context.Context, in *ListVolumeAttachmentsRequest, opts ...grpc.CallOption) (*ListVolumeAttachmentsResponse, error)
	// --- MCPs ---
	CreateMcp(ctx context.Context, in *CreateMcpRequest, opts ...grpc.CallOption) (*CreateMcpResponse, error)
	GetMcp(ctx context.Context, in *GetMcpRequest, opts ...grpc.CallOption) (*GetMcpResponse, error)
	UpdateMcp(ctx context.Context, in *UpdateMcpRequest, opts ...grpc.CallOption) (*UpdateMcpResponse, error)
	DeleteMcp(ctx context.Context, in *DeleteMcpRequest, opts ...grpc.CallOption) (*DeleteMcpResponse, error)
	ListMcps(ctx context.Context, in *ListMcpsRequest, opts ...grpc.CallOption) (*ListMcpsResponse, error)
	// --- Skills ---
	CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...grpc.CallOption) (*CreateSkillResponse, error)
	GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*GetSkillResponse, error)
	UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...grpc.CallOption) (*UpdateSkillResponse, error)
	DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*DeleteSkillResponse, error)
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	// --- Hooks ---
	CreateHook(ctx context.Context, in *CreateHookRequest, opts ...grpc.CallOption) (*CreateHookResponse, error)
	GetHook(ctx context.Context, in *GetHookRequest, opts ...grpc.CallOption) (*GetHookResponse, error)
	UpdateHook(ctx context.Context, in *UpdateHookRequest, opts ...grpc.CallOption) (*UpdateHookResponse, error)
	DeleteHook(ctx context.Context, in *DeleteHookRequest, opts ...grpc.CallOption) (*DeleteHookResponse, error)
	ListHooks(ctx context.Context, in *ListHooksRequest, opts ...grpc.CallOption) (*ListHooksResponse, error)
	// --- Envs ---
	CreateEnv(ctx context.Context, in *CreateEnvRequest, opts ...grpc.CallOption) (*CreateEnvResponse, error)
	GetEnv(ctx context.Context, in *GetEnvRequest, opts ...grpc.CallOption) (*GetEnvResponse, error)
	UpdateEnv(ctx context.Context, in *UpdateEnvRequest, opts ...grpc.CallOption) (*UpdateEnvResponse, error)
	DeleteEnv(ctx context.Context, in *DeleteEnvRequest, opts ...grpc.CallOption) (*DeleteEnvResponse, error)
	ListEnvs(ctx context.Context, in *ListEnvsRequest, opts ...grpc.CallOption) (*ListEnvsResponse, error)
	// --- Init Scripts ---
	CreateInitScript(ctx context.Context, in *CreateInitScriptRequest, opts ...grpc.CallOption) (*CreateInitScriptResponse, error)
	GetInitScript(ctx context.Context, in *GetInitScriptRequest, opts ...grpc.CallOption) (*GetInitScriptResponse, error)
	UpdateInitScript(ctx context.Context, in *UpdateInitScriptRequest, opts ...grpc.CallOption) (*UpdateInitScriptResponse, error)
	DeleteInitScript(ctx context.Context, in *DeleteInitScriptRequest, opts ...grpc.CallOption) (*DeleteInitScriptResponse, error)
	ListInitScripts(ctx context.Context, in *ListInitScriptsRequest, opts ...grpc.CallOption) (*ListInitScriptsResponse, error)
	// --- Image Pull Secret Attachments (no Update - immutable) ---
	CreateImagePullSecretAttachment(ctx context.Context, in *CreateImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*CreateImagePullSecretAttachmentResponse, error)
	GetImagePullSecretAttachment(ctx context.Context, in *GetImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*GetImagePullSecretAttachmentResponse, error)
	DeleteImagePullSecretAttachment(ctx context.Context, in *DeleteImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*DeleteImagePullSecretAttachmentResponse, error)
	ListImagePullSecretAttachments(ctx context.Context, in *ListImagePullSecretAttachmentsRequest, opts ...grpc.CallOption) (*ListImagePullSecretAttachmentsResponse, error)
}

type agentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentsServiceClient(cc grpc.ClientConnInterface) AgentsServiceClient {
	return &agentsServiceClient{cc}
}

func (c *agentsServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentResponse)
	err := c.cc.Invoke(ctx, AgentsService_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentResponse)
	err := c.cc.Invoke(ctx, AgentsService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ResolveAgentIdentity(ctx context.Context, in *ResolveAgentIdentityRequest, opts ...grpc.CallOption) (*ResolveAgentIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAgentIdentityResponse)
	err := c.cc.Invoke(ctx, AgentsService_ResolveAgentIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAgentResponse)
	err := c.cc.Invoke(ctx, AgentsService_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAgentResponse)
	err := c.cc.Invoke(ctx, AgentsService_DeleteAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) SetAgentRole(ctx context.Context, in *SetAgentRoleRequest, opts ...grpc.CallOption) (*SetAgentRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAgentRoleResponse)
	err := c.cc.Invoke(ctx, AgentsService_SetAgentRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) RemoveAgentRole(ctx context.Context, in *RemoveAgentRoleRequest, opts ...grpc.CallOption) (*RemoveAgentRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAgentRoleResponse)
	err := c.cc.Invoke(ctx, AgentsService_RemoveAgentRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListAgentRoles(ctx context.Context, in *ListAgentRolesRequest, opts ...grpc.CallOption) (*ListAgentRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentRolesResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListAgentRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListMyAgentRoles(ctx context.Context, in *ListMyAgentRolesRequest, opts ...grpc.CallOption) (*ListMyAgentRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyAgentRolesResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListMyAgentRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, AgentsService_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolumeResponse)
	err := c.cc.Invoke(ctx, AgentsService_GetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) UpdateVolume(ctx context.Context, in *UpdateVolumeRequest, opts ...grpc.CallOption) (*UpdateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVolumeResponse)
	err := c.cc.Invoke(ctx, AgentsService_UpdateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVolumeResponse)
	err := c.cc.Invoke(ctx, AgentsService_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CreateVolumeAttachment(ctx context.Context, in *CreateVolumeAttachmentRequest, opts ...grpc.CallOption) (*CreateVolumeAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsService_CreateVolumeAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetVolumeAttachment(ctx context.Context, in *GetVolumeAttachmentRequest, opts ...grpc.CallOption) (*GetVolumeAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolumeAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsService_GetVolumeAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) DeleteVolumeAttachment(ctx context.Context, in *DeleteVolumeAttachmentRequest, opts ...grpc.CallOption) (*DeleteVolumeAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVolumeAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsService_DeleteVolumeAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListVolumeAttachments(ctx context.Context, in *ListVolumeAttachmentsRequest, opts ...grpc.CallOption) (*ListVolumeAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumeAttachmentsResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListVolumeAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CreateMcp(ctx context.Context, in *CreateMcpRequest, opts ...grpc.CallOption) (*CreateMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMcpResponse)
	err := c.cc.Invoke(ctx, AgentsService_CreateMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetMcp(ctx context.Context, in *GetMcpRequest, opts ...grpc.CallOption) (*GetMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMcpResponse)
	err := c.cc.Invoke(ctx, AgentsService_GetMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) UpdateMcp(ctx context.Context, in *UpdateMcpRequest, opts ...grpc.CallOption) (*UpdateMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMcpResponse)
	err := c.cc.Invoke(ctx, AgentsService_UpdateMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) DeleteMcp(ctx context.Context, in *DeleteMcpRequest, opts ...grpc.CallOption) (*DeleteMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMcpResponse)
	err := c.cc.Invoke(ctx, AgentsService_DeleteMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListMcps(ctx context.Context, in *ListMcpsRequest, opts ...grpc.CallOption) (*ListMcpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMcpsResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListMcps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...grpc.CallOption) (*CreateSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSkillResponse)
	err := c.cc.Invoke(ctx, AgentsService_CreateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*GetSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkillResponse)
	err := c.cc.Invoke(ctx, AgentsService_GetSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) UpdateSkill(ctx context.Context, in *UpdateSkillRequest, opts ...grpc.CallOption) (*UpdateSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSkillResponse)
	err := c.cc.Invoke(ctx, AgentsService_UpdateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*DeleteSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSkillResponse)
	err := c.cc.Invoke(ctx, AgentsService_DeleteSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CreateHook(ctx context.Context, in *CreateHookRequest, opts ...grpc.CallOption) (*CreateHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHookResponse)
	err := c.cc.Invoke(ctx, AgentsService_CreateHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetHook(ctx context.Context, in *GetHookRequest, opts ...grpc.CallOption) (*GetHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHookResponse)
	err := c.cc.Invoke(ctx, AgentsService_GetHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) UpdateHook(ctx context.Context, in *UpdateHookRequest, opts ...grpc.CallOption) (*UpdateHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHookResponse)
	err := c.cc.Invoke(ctx, AgentsService_UpdateHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) DeleteHook(ctx context.Context, in *DeleteHookRequest, opts ...grpc.CallOption) (*DeleteHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHookResponse)
	err := c.cc.Invoke(ctx, AgentsService_DeleteHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListHooks(ctx context.Context, in *ListHooksRequest, opts ...grpc.CallOption) (*ListHooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHooksResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListHooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CreateEnv(ctx context.Context, in *CreateEnvRequest, opts ...grpc.CallOption) (*CreateEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnvResponse)
	err := c.cc.Invoke(ctx, AgentsService_CreateEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetEnv(ctx context.Context, in *GetEnvRequest, opts ...grpc.CallOption) (*GetEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnvResponse)
	err := c.cc.Invoke(ctx, AgentsService_GetEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) UpdateEnv(ctx context.Context, in *UpdateEnvRequest, opts ...grpc.CallOption) (*UpdateEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEnvResponse)
	err := c.cc.Invoke(ctx, AgentsService_UpdateEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) DeleteEnv(ctx context.Context, in *DeleteEnvRequest, opts ...grpc.CallOption) (*DeleteEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEnvResponse)
	err := c.cc.Invoke(ctx, AgentsService_DeleteEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListEnvs(ctx context.Context, in *ListEnvsRequest, opts ...grpc.CallOption) (*ListEnvsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnvsResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListEnvs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CreateInitScript(ctx context.Context, in *CreateInitScriptRequest, opts ...grpc.CallOption) (*CreateInitScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInitScriptResponse)
	err := c.cc.Invoke(ctx, AgentsService_CreateInitScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetInitScript(ctx context.Context, in *GetInitScriptRequest, opts ...grpc.CallOption) (*GetInitScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInitScriptResponse)
	err := c.cc.Invoke(ctx, AgentsService_GetInitScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) UpdateInitScript(ctx context.Context, in *UpdateInitScriptRequest, opts ...grpc.CallOption) (*UpdateInitScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInitScriptResponse)
	err := c.cc.Invoke(ctx, AgentsService_UpdateInitScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) DeleteInitScript(ctx context.Context, in *DeleteInitScriptRequest, opts ...grpc.CallOption) (*DeleteInitScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInitScriptResponse)
	err := c.cc.Invoke(ctx, AgentsService_DeleteInitScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListInitScripts(ctx context.Context, in *ListInitScriptsRequest, opts ...grpc.CallOption) (*ListInitScriptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInitScriptsResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListInitScripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CreateImagePullSecretAttachment(ctx context.Context, in *CreateImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*CreateImagePullSecretAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateImagePullSecretAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsService_CreateImagePullSecretAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetImagePullSecretAttachment(ctx context.Context, in *GetImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*GetImagePullSecretAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImagePullSecretAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsService_GetImagePullSecretAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) DeleteImagePullSecretAttachment(ctx context.Context, in *DeleteImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*DeleteImagePullSecretAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteImagePullSecretAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsService_DeleteImagePullSecretAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListImagePullSecretAttachments(ctx context.Context, in *ListImagePullSecretAttachmentsRequest, opts ...grpc.CallOption) (*ListImagePullSecretAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagePullSecretAttachmentsResponse)
	err := c.cc.Invoke(ctx, AgentsService_ListImagePullSecretAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentsServiceServer is the server API for AgentsService service.
// All implementations should embed UnimplementedAgentsServiceServer
// for forward compatibility.
//
// AgentsService manages agent resources: agents, volumes, volume attachments,
// MCP servers, skills, hooks, environment variables, and init scripts.
//
// This is a control-plane service. It stores desired state;
// other services reconcile toward it.
type AgentsServiceServer interface {
	// --- Agents ---
	CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error)
	GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error)
	// Resolve an agent and organization by identity ID.
	ResolveAgentIdentity(context.Context, *ResolveAgentIdentityRequest) (*ResolveAgentIdentityResponse, error)
	UpdateAgent(context.Context, *UpdateAgentRequest) (*UpdateAgentResponse, error)
	DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentResponse, error)
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	SetAgentRole(context.Context, *SetAgentRoleRequest) (*SetAgentRoleResponse, error)
	RemoveAgentRole(context.Context, *RemoveAgentRoleRequest) (*RemoveAgentRoleResponse, error)
	ListAgentRoles(context.Context, *ListAgentRolesRequest) (*ListAgentRolesResponse, error)
	ListMyAgentRoles(context.Context, *ListMyAgentRolesRequest) (*ListMyAgentRolesResponse, error)
	// --- Volumes ---
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error)
	UpdateVolume(context.Context, *UpdateVolumeRequest) (*UpdateVolumeResponse, error)
	DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error)
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	// --- Volume Attachments (no Update) ---
	CreateVolumeAttachment(context.Context, *CreateVolumeAttachmentRequest) (*CreateVolumeAttachmentResponse, error)
	GetVolumeAttachment(context.Context, *GetVolumeAttachmentRequest) (*GetVolumeAttachmentResponse, error)
	DeleteVolumeAttachment(context.Context, *DeleteVolumeAttachmentRequest) (*DeleteVolumeAttachmentResponse, error)
	ListVolumeAttachments(context.Context, *ListVolumeAttachmentsRequest) (*ListVolumeAttachmentsResponse, error)
	// --- MCPs ---
	CreateMcp(context.Context, *CreateMcpRequest) (*CreateMcpResponse, error)
	GetMcp(context.Context, *GetMcpRequest) (*GetMcpResponse, error)
	UpdateMcp(context.Context, *UpdateMcpRequest) (*UpdateMcpResponse, error)
	DeleteMcp(context.Context, *DeleteMcpRequest) (*DeleteMcpResponse, error)
	ListMcps(context.Context, *ListMcpsRequest) (*ListMcpsResponse, error)
	// --- Skills ---
	CreateSkill(context.Context, *CreateSkillRequest) (*CreateSkillResponse, error)
	GetSkill(context.Context, *GetSkillRequest) (*GetSkillResponse, error)
	UpdateSkill(context.Context, *UpdateSkillRequest) (*UpdateSkillResponse, error)
	DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillResponse, error)
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	// --- Hooks ---
	CreateHook(context.Context, *CreateHookRequest) (*CreateHookResponse, error)
	GetHook(context.Context, *GetHookRequest) (*GetHookResponse, error)
	UpdateHook(context.Context, *UpdateHookRequest) (*UpdateHookResponse, error)
	DeleteHook(context.Context, *DeleteHookRequest) (*DeleteHookResponse, error)
	ListHooks(context.Context, *ListHooksRequest) (*ListHooksResponse, error)
	// --- Envs ---
	CreateEnv(context.Context, *CreateEnvRequest) (*CreateEnvResponse, error)
	GetEnv(context.Context, *GetEnvRequest) (*GetEnvResponse, error)
	UpdateEnv(context.Context, *UpdateEnvRequest) (*UpdateEnvResponse, error)
	DeleteEnv(context.Context, *DeleteEnvRequest) (*DeleteEnvResponse, error)
	ListEnvs(context.Context, *ListEnvsRequest) (*ListEnvsResponse, error)
	// --- Init Scripts ---
	CreateInitScript(context.Context, *CreateInitScriptRequest) (*CreateInitScriptResponse, error)
	GetInitScript(context.Context, *GetInitScriptRequest) (*GetInitScriptResponse, error)
	UpdateInitScript(context.Context, *UpdateInitScriptRequest) (*UpdateInitScriptResponse, error)
	DeleteInitScript(context.Context, *DeleteInitScriptRequest) (*DeleteInitScriptResponse, error)
	ListInitScripts(context.Context, *ListInitScriptsRequest) (*ListInitScriptsResponse, error)
	// --- Image Pull Secret Attachments (no Update - immutable) ---
	CreateImagePullSecretAttachment(context.Context, *CreateImagePullSecretAttachmentRequest) (*CreateImagePullSecretAttachmentResponse, error)
	GetImagePullSecretAttachment(context.Context, *GetImagePullSecretAttachmentRequest) (*GetImagePullSecretAttachmentResponse, error)
	DeleteImagePullSecretAttachment(context.Context, *DeleteImagePullSecretAttachmentRequest) (*DeleteImagePullSecretAttachmentResponse, error)
	ListImagePullSecretAttachments(context.Context, *ListImagePullSecretAttachmentsRequest) (*ListImagePullSecretAttachmentsResponse, error)
}

// UnimplementedAgentsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentsServiceServer struct{}

func (UnimplementedAgentsServiceServer) CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedAgentsServiceServer) GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentsServiceServer) ResolveAgentIdentity(context.Context, *ResolveAgentIdentityRequest) (*ResolveAgentIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAgentIdentity not implemented")
}
func (UnimplementedAgentsServiceServer) UpdateAgent(context.Context, *UpdateAgentRequest) (*UpdateAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedAgentsServiceServer) DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAgent not implemented")
}
func (UnimplementedAgentsServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentsServiceServer) SetAgentRole(context.Context, *SetAgentRoleRequest) (*SetAgentRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAgentRole not implemented")
}
func (UnimplementedAgentsServiceServer) RemoveAgentRole(context.Context, *RemoveAgentRoleRequest) (*RemoveAgentRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAgentRole not implemented")
}
func (UnimplementedAgentsServiceServer) ListAgentRoles(context.Context, *ListAgentRolesRequest) (*ListAgentRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentRoles not implemented")
}
func (UnimplementedAgentsServiceServer) ListMyAgentRoles(context.Context, *ListMyAgentRolesRequest) (*ListMyAgentRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyAgentRoles not implemented")
}
func (UnimplementedAgentsServiceServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedAgentsServiceServer) GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolume not implemented")
}
func (UnimplementedAgentsServiceServer) UpdateVolume(context.Context, *UpdateVolumeRequest) (*UpdateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVolume not implemented")
}
func (UnimplementedAgentsServiceServer) DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedAgentsServiceServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedAgentsServiceServer) CreateVolumeAttachment(context.Context, *CreateVolumeAttachmentRequest) (*CreateVolumeAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolumeAttachment not implemented")
}
func (UnimplementedAgentsServiceServer) GetVolumeAttachment(context.Context, *GetVolumeAttachmentRequest) (*GetVolumeAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolumeAttachment not implemented")
}
func (UnimplementedAgentsServiceServer) DeleteVolumeAttachment(context.Context, *DeleteVolumeAttachmentRequest) (*DeleteVolumeAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolumeAttachment not implemented")
}
func (UnimplementedAgentsServiceServer) ListVolumeAttachments(context.Context, *ListVolumeAttachmentsRequest) (*ListVolumeAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumeAttachments not implemented")
}
func (UnimplementedAgentsServiceServer) CreateMcp(context.Context, *CreateMcpRequest) (*CreateMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMcp not implemented")
}
func (UnimplementedAgentsServiceServer) GetMcp(context.Context, *GetMcpRequest) (*GetMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMcp not implemented")
}
func (UnimplementedAgentsServiceServer) UpdateMcp(context.Context, *UpdateMcpRequest) (*UpdateMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMcp not implemented")
}
func (UnimplementedAgentsServiceServer) DeleteMcp(context.Context, *DeleteMcpRequest) (*DeleteMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMcp not implemented")
}
func (UnimplementedAgentsServiceServer) ListMcps(context.Context, *ListMcpsRequest) (*ListMcpsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMcps not implemented")
}
func (UnimplementedAgentsServiceServer) CreateSkill(context.Context, *CreateSkillRequest) (*CreateSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSkill not implemented")
}
func (UnimplementedAgentsServiceServer) GetSkill(context.Context, *GetSkillRequest) (*GetSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkill not implemented")
}
func (UnimplementedAgentsServiceServer) UpdateSkill(context.Context, *UpdateSkillRequest) (*UpdateSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSkill not implemented")
}
func (UnimplementedAgentsServiceServer) DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSkill not implemented")
}
func (UnimplementedAgentsServiceServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedAgentsServiceServer) CreateHook(context.Context, *CreateHookRequest) (*CreateHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHook not implemented")
}
func (UnimplementedAgentsServiceServer) GetHook(context.Context, *GetHookRequest) (*GetHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHook not implemented")
}
func (UnimplementedAgentsServiceServer) UpdateHook(context.Context, *UpdateHookRequest) (*UpdateHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHook not implemented")
}
func (UnimplementedAgentsServiceServer) DeleteHook(context.Context, *DeleteHookRequest) (*DeleteHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHook not implemented")
}
func (UnimplementedAgentsServiceServer) ListHooks(context.Context, *ListHooksRequest) (*ListHooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHooks not implemented")
}
func (UnimplementedAgentsServiceServer) CreateEnv(context.Context, *CreateEnvRequest) (*CreateEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnv not implemented")
}
func (UnimplementedAgentsServiceServer) GetEnv(context.Context, *GetEnvRequest) (*GetEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnv not implemented")
}
func (UnimplementedAgentsServiceServer) UpdateEnv(context.Context, *UpdateEnvRequest) (*UpdateEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnv not implemented")
}
func (UnimplementedAgentsServiceServer) DeleteEnv(context.Context, *DeleteEnvRequest) (*DeleteEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEnv not implemented")
}
func (UnimplementedAgentsServiceServer) ListEnvs(context.Context, *ListEnvsRequest) (*ListEnvsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnvs not implemented")
}
func (UnimplementedAgentsServiceServer) CreateInitScript(context.Context, *CreateInitScriptRequest) (*CreateInitScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInitScript not implemented")
}
func (UnimplementedAgentsServiceServer) GetInitScript(context.Context, *GetInitScriptRequest) (*GetInitScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInitScript not implemented")
}
func (UnimplementedAgentsServiceServer) UpdateInitScript(context.Context, *UpdateInitScriptRequest) (*UpdateInitScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInitScript not implemented")
}
func (UnimplementedAgentsServiceServer) DeleteInitScript(context.Context, *DeleteInitScriptRequest) (*DeleteInitScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInitScript not implemented")
}
func (UnimplementedAgentsServiceServer) ListInitScripts(context.Context, *ListInitScriptsRequest) (*ListInitScriptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInitScripts not implemented")
}
func (UnimplementedAgentsServiceServer) CreateImagePullSecretAttachment(context.Context, *CreateImagePullSecretAttachmentRequest) (*CreateImagePullSecretAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateImagePullSecretAttachment not implemented")
}
func (UnimplementedAgentsServiceServer) GetImagePullSecretAttachment(context.Context, *GetImagePullSecretAttachmentRequest) (*GetImagePullSecretAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImagePullSecretAttachment not implemented")
}
func (UnimplementedAgentsServiceServer) DeleteImagePullSecretAttachment(context.Context, *DeleteImagePullSecretAttachmentRequest) (*DeleteImagePullSecretAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImagePullSecretAttachment not implemented")
}
func (UnimplementedAgentsServiceServer) ListImagePullSecretAttachments(context.Context, *ListImagePullSecretAttachmentsRequest) (*ListImagePullSecretAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImagePullSecretAttachments not implemented")
}
func (UnimplementedAgentsServiceServer) testEmbeddedByValue() {}

// UnsafeAgentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentsServiceServer will
// result in compilation errors.
type UnsafeAgentsServiceServer interface {
	mustEmbedUnimplementedAgentsServiceServer()
}

func RegisterAgentsServiceServer(s grpc.ServiceRegistrar, srv AgentsServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentsService_ServiceDesc, srv)
}

func _AgentsService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ResolveAgentIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAgentIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ResolveAgentIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ResolveAgentIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ResolveAgentIdentity(ctx, req.(*ResolveAgentIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_DeleteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_SetAgentRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAgentRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).SetAgentRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_SetAgentRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).SetAgentRole(ctx, req.(*SetAgentRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_RemoveAgentRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAgentRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).RemoveAgentRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_RemoveAgentRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).RemoveAgentRole(ctx, req.(*RemoveAgentRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListAgentRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListAgentRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListAgentRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListAgentRoles(ctx, req.(*ListAgentRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListMyAgentRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyAgentRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListMyAgentRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListMyAgentRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListMyAgentRoles(ctx, req.(*ListMyAgentRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetVolume(ctx, req.(*GetVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_UpdateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).UpdateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_UpdateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).UpdateVolume(ctx, req.(*UpdateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).DeleteVolume(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CreateVolumeAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateVolumeAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateVolumeAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateVolumeAttachment(ctx, req.(*CreateVolumeAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetVolumeAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetVolumeAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetVolumeAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetVolumeAttachment(ctx, req.(*GetVolumeAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_DeleteVolumeAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).DeleteVolumeAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_DeleteVolumeAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).DeleteVolumeAttachment(ctx, req.(*DeleteVolumeAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListVolumeAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumeAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListVolumeAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListVolumeAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListVolumeAttachments(ctx, req.(*ListVolumeAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CreateMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateMcp(ctx, req.(*CreateMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetMcp(ctx, req.(*GetMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_UpdateMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).UpdateMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_UpdateMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).UpdateMcp(ctx, req.(*UpdateMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_DeleteMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).DeleteMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_DeleteMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).DeleteMcp(ctx, req.(*DeleteMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListMcps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMcpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListMcps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListMcps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListMcps(ctx, req.(*ListMcpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CreateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateSkill(ctx, req.(*CreateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetSkill(ctx, req.(*GetSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_UpdateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).UpdateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_UpdateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).UpdateSkill(ctx, req.(*UpdateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_DeleteSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).DeleteSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_DeleteSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).DeleteSkill(ctx, req.(*DeleteSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CreateHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateHook(ctx, req.(*CreateHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetHook(ctx, req.(*GetHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_UpdateHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).UpdateHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_UpdateHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).UpdateHook(ctx, req.(*UpdateHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_DeleteHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).DeleteHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_DeleteHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).DeleteHook(ctx, req.(*DeleteHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListHooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListHooks(ctx, req.(*ListHooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CreateEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateEnv(ctx, req.(*CreateEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetEnv(ctx, req.(*GetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_UpdateEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).UpdateEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_UpdateEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).UpdateEnv(ctx, req.(*UpdateEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_DeleteEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).DeleteEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_DeleteEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).DeleteEnv(ctx, req.(*DeleteEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListEnvs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListEnvs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListEnvs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListEnvs(ctx, req.(*ListEnvsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CreateInitScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInitScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateInitScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateInitScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateInitScript(ctx, req.(*CreateInitScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetInitScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInitScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetInitScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetInitScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetInitScript(ctx, req.(*GetInitScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_UpdateInitScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInitScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).UpdateInitScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_UpdateInitScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).UpdateInitScript(ctx, req.(*UpdateInitScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_DeleteInitScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInitScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).DeleteInitScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_DeleteInitScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).DeleteInitScript(ctx, req.(*DeleteInitScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListInitScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInitScriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListInitScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListInitScripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListInitScripts(ctx, req.(*ListInitScriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CreateImagePullSecretAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImagePullSecretAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateImagePullSecretAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateImagePullSecretAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateImagePullSecretAttachment(ctx, req.(*CreateImagePullSecretAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetImagePullSecretAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImagePullSecretAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetImagePullSecretAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetImagePullSecretAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetImagePullSecretAttachment(ctx, req.(*GetImagePullSecretAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_DeleteImagePullSecretAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImagePullSecretAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).DeleteImagePullSecretAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_DeleteImagePullSecretAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).DeleteImagePullSecretAttachment(ctx, req.(*DeleteImagePullSecretAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListImagePullSecretAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagePullSecretAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListImagePullSecretAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListImagePullSecretAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListImagePullSecretAttachments(ctx, req.(*ListImagePullSecretAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentsService_ServiceDesc is the grpc.ServiceDesc for AgentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.agents.v1.AgentsService",
	HandlerType: (*AgentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _AgentsService_CreateAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentsService_GetAgent_Handler,
		},
		{
			MethodName: "ResolveAgentIdentity",
			Handler:    _AgentsService_ResolveAgentIdentity_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _AgentsService_UpdateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _AgentsService_DeleteAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentsService_ListAgents_Handler,
		},
		{
			MethodName: "SetAgentRole",
			Handler:    _AgentsService_SetAgentRole_Handler,
		},
		{
			MethodName: "RemoveAgentRole",
			Handler:    _AgentsService_RemoveAgentRole_Handler,
		},
		{
			MethodName: "ListAgentRoles",
			Handler:    _AgentsService_ListAgentRoles_Handler,
		},
		{
			MethodName: "ListMyAgentRoles",
			Handler:    _AgentsService_ListMyAgentRoles_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _AgentsService_CreateVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _AgentsService_GetVolume_Handler,
		},
		{
			MethodName: "UpdateVolume",
			Handler:    _AgentsService_UpdateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _AgentsService_DeleteVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _AgentsService_ListVolumes_Handler,
		},
		{
			MethodName: "CreateVolumeAttachment",
			Handler:    _AgentsService_CreateVolumeAttachment_Handler,
		},
		{
			MethodName: "GetVolumeAttachment",
			Handler:    _AgentsService_GetVolumeAttachment_Handler,
		},
		{
			MethodName: "DeleteVolumeAttachment",
			Handler:    _AgentsService_DeleteVolumeAttachment_Handler,
		},
		{
			MethodName: "ListVolumeAttachments",
			Handler:    _AgentsService_ListVolumeAttachments_Handler,
		},
		{
			MethodName: "CreateMcp",
			Handler:    _AgentsService_CreateMcp_Handler,
		},
		{
			MethodName: "GetMcp",
			Handler:    _AgentsService_GetMcp_Handler,
		},
		{
			MethodName: "UpdateMcp",
			Handler:    _AgentsService_UpdateMcp_Handler,
		},
		{
			MethodName: "DeleteMcp",
			Handler:    _AgentsService_DeleteMcp_Handler,
		},
		{
			MethodName: "ListMcps",
			Handler:    _AgentsService_ListMcps_Handler,
		},
		{
			MethodName: "CreateSkill",
			Handler:    _AgentsService_CreateSkill_Handler,
		},
		{
			MethodName: "GetSkill",
			Handler:    _AgentsService_GetSkill_Handler,
		},
		{
			MethodName: "UpdateSkill",
			Handler:    _AgentsService_UpdateSkill_Handler,
		},
		{
			MethodName: "DeleteSkill",
			Handler:    _AgentsService_DeleteSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _AgentsService_ListSkills_Handler,
		},
		{
			MethodName: "CreateHook",
			Handler:    _AgentsService_CreateHook_Handler,
		},
		{
			MethodName: "GetHook",
			Handler:    _AgentsService_GetHook_Handler,
		},
		{
			MethodName: "UpdateHook",
			Handler:    _AgentsService_UpdateHook_Handler,
		},
		{
			MethodName: "DeleteHook",
			Handler:    _AgentsService_DeleteHook_Handler,
		},
		{
			MethodName: "ListHooks",
			Handler:    _AgentsService_ListHooks_Handler,
		},
		{
			MethodName: "CreateEnv",
			Handler:    _AgentsService_CreateEnv_Handler,
		},
		{
			MethodName: "GetEnv",
			Handler:    _AgentsService_GetEnv_Handler,
		},
		{
			MethodName: "UpdateEnv",
			Handler:    _AgentsService_UpdateEnv_Handler,
		},
		{
			MethodName: "DeleteEnv",
			Handler:    _AgentsService_DeleteEnv_Handler,
		},
		{
			MethodName: "ListEnvs",
			Handler:    _AgentsService_ListEnvs_Handler,
		},
		{
			MethodName: "CreateInitScript",
			Handler:    _AgentsService_CreateInitScript_Handler,
		},
		{
			MethodName: "GetInitScript",
			Handler:    _AgentsService_GetInitScript_Handler,
		},
		{
			MethodName: "UpdateInitScript",
			Handler:    _AgentsService_UpdateInitScript_Handler,
		},
		{
			MethodName: "DeleteInitScript",
			Handler:    _AgentsService_DeleteInitScript_Handler,
		},
		{
			MethodName: "ListInitScripts",
			Handler:    _AgentsService_ListInitScripts_Handler,
		},
		{
			MethodName: "CreateImagePullSecretAttachment",
			Handler:    _AgentsService_CreateImagePullSecretAttachment_Handler,
		},
		{
			MethodName: "GetImagePullSecretAttachment",
			Handler:    _AgentsService_GetImagePullSecretAttachment_Handler,
		},
		{
			MethodName: "DeleteImagePullSecretAttachment",
			Handler:    _AgentsService_DeleteImagePullSecretAttachment_Handler,
		},
		{
			MethodName: "ListImagePullSecretAttachments",
			Handler:    _AgentsService_ListImagePullSecretAttachments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/agents/v1/agents.proto",
}
