// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: agynio/api/egress/v1/egress.proto

package egressv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EgressRulesService_CreateEgressRule_FullMethodName            = "/agynio.api.egress.v1.EgressRulesService/CreateEgressRule"
	EgressRulesService_GetEgressRule_FullMethodName               = "/agynio.api.egress.v1.EgressRulesService/GetEgressRule"
	EgressRulesService_ListEgressRules_FullMethodName             = "/agynio.api.egress.v1.EgressRulesService/ListEgressRules"
	EgressRulesService_UpdateEgressRule_FullMethodName            = "/agynio.api.egress.v1.EgressRulesService/UpdateEgressRule"
	EgressRulesService_DeleteEgressRule_FullMethodName            = "/agynio.api.egress.v1.EgressRulesService/DeleteEgressRule"
	EgressRulesService_CreateEgressRuleAttachment_FullMethodName  = "/agynio.api.egress.v1.EgressRulesService/CreateEgressRuleAttachment"
	EgressRulesService_DeleteEgressRuleAttachment_FullMethodName  = "/agynio.api.egress.v1.EgressRulesService/DeleteEgressRuleAttachment"
	EgressRulesService_ListEgressRuleAttachments_FullMethodName   = "/agynio.api.egress.v1.EgressRulesService/ListEgressRuleAttachments"
	EgressRulesService_ListEgressRulesByAgent_FullMethodName      = "/agynio.api.egress.v1.EgressRulesService/ListEgressRulesByAgent"
	EgressRulesService_CountRulesReferencingSecret_FullMethodName = "/agynio.api.egress.v1.EgressRulesService/CountRulesReferencingSecret"
)

// EgressRulesServiceClient is the client API for EgressRulesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EgressRulesService manages egress rules and agent attachments.
type EgressRulesServiceClient interface {
	// --- Egress Rules ---
	CreateEgressRule(ctx context.Context, in *CreateEgressRuleRequest, opts ...grpc.CallOption) (*CreateEgressRuleResponse, error)
	GetEgressRule(ctx context.Context, in *GetEgressRuleRequest, opts ...grpc.CallOption) (*GetEgressRuleResponse, error)
	ListEgressRules(ctx context.Context, in *ListEgressRulesRequest, opts ...grpc.CallOption) (*ListEgressRulesResponse, error)
	UpdateEgressRule(ctx context.Context, in *UpdateEgressRuleRequest, opts ...grpc.CallOption) (*UpdateEgressRuleResponse, error)
	DeleteEgressRule(ctx context.Context, in *DeleteEgressRuleRequest, opts ...grpc.CallOption) (*DeleteEgressRuleResponse, error)
	// --- Egress Rule Attachments ---
	CreateEgressRuleAttachment(ctx context.Context, in *CreateEgressRuleAttachmentRequest, opts ...grpc.CallOption) (*CreateEgressRuleAttachmentResponse, error)
	DeleteEgressRuleAttachment(ctx context.Context, in *DeleteEgressRuleAttachmentRequest, opts ...grpc.CallOption) (*DeleteEgressRuleAttachmentResponse, error)
	ListEgressRuleAttachments(ctx context.Context, in *ListEgressRuleAttachmentsRequest, opts ...grpc.CallOption) (*ListEgressRuleAttachmentsResponse, error)
	// --- Internal ---
	ListEgressRulesByAgent(ctx context.Context, in *ListEgressRulesByAgentRequest, opts ...grpc.CallOption) (*ListEgressRulesByAgentResponse, error)
	CountRulesReferencingSecret(ctx context.Context, in *CountRulesReferencingSecretRequest, opts ...grpc.CallOption) (*CountRulesReferencingSecretResponse, error)
}

type egressRulesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEgressRulesServiceClient(cc grpc.ClientConnInterface) EgressRulesServiceClient {
	return &egressRulesServiceClient{cc}
}

func (c *egressRulesServiceClient) CreateEgressRule(ctx context.Context, in *CreateEgressRuleRequest, opts ...grpc.CallOption) (*CreateEgressRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEgressRuleResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_CreateEgressRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressRulesServiceClient) GetEgressRule(ctx context.Context, in *GetEgressRuleRequest, opts ...grpc.CallOption) (*GetEgressRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEgressRuleResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_GetEgressRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressRulesServiceClient) ListEgressRules(ctx context.Context, in *ListEgressRulesRequest, opts ...grpc.CallOption) (*ListEgressRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEgressRulesResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_ListEgressRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressRulesServiceClient) UpdateEgressRule(ctx context.Context, in *UpdateEgressRuleRequest, opts ...grpc.CallOption) (*UpdateEgressRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEgressRuleResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_UpdateEgressRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressRulesServiceClient) DeleteEgressRule(ctx context.Context, in *DeleteEgressRuleRequest, opts ...grpc.CallOption) (*DeleteEgressRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEgressRuleResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_DeleteEgressRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressRulesServiceClient) CreateEgressRuleAttachment(ctx context.Context, in *CreateEgressRuleAttachmentRequest, opts ...grpc.CallOption) (*CreateEgressRuleAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEgressRuleAttachmentResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_CreateEgressRuleAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressRulesServiceClient) DeleteEgressRuleAttachment(ctx context.Context, in *DeleteEgressRuleAttachmentRequest, opts ...grpc.CallOption) (*DeleteEgressRuleAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEgressRuleAttachmentResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_DeleteEgressRuleAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressRulesServiceClient) ListEgressRuleAttachments(ctx context.Context, in *ListEgressRuleAttachmentsRequest, opts ...grpc.CallOption) (*ListEgressRuleAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEgressRuleAttachmentsResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_ListEgressRuleAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressRulesServiceClient) ListEgressRulesByAgent(ctx context.Context, in *ListEgressRulesByAgentRequest, opts ...grpc.CallOption) (*ListEgressRulesByAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEgressRulesByAgentResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_ListEgressRulesByAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressRulesServiceClient) CountRulesReferencingSecret(ctx context.Context, in *CountRulesReferencingSecretRequest, opts ...grpc.CallOption) (*CountRulesReferencingSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountRulesReferencingSecretResponse)
	err := c.cc.Invoke(ctx, EgressRulesService_CountRulesReferencingSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgressRulesServiceServer is the server API for EgressRulesService service.
// All implementations should embed UnimplementedEgressRulesServiceServer
// for forward compatibility.
//
// EgressRulesService manages egress rules and agent attachments.
type EgressRulesServiceServer interface {
	// --- Egress Rules ---
	CreateEgressRule(context.Context, *CreateEgressRuleRequest) (*CreateEgressRuleResponse, error)
	GetEgressRule(context.Context, *GetEgressRuleRequest) (*GetEgressRuleResponse, error)
	ListEgressRules(context.Context, *ListEgressRulesRequest) (*ListEgressRulesResponse, error)
	UpdateEgressRule(context.Context, *UpdateEgressRuleRequest) (*UpdateEgressRuleResponse, error)
	DeleteEgressRule(context.Context, *DeleteEgressRuleRequest) (*DeleteEgressRuleResponse, error)
	// --- Egress Rule Attachments ---
	CreateEgressRuleAttachment(context.Context, *CreateEgressRuleAttachmentRequest) (*CreateEgressRuleAttachmentResponse, error)
	DeleteEgressRuleAttachment(context.Context, *DeleteEgressRuleAttachmentRequest) (*DeleteEgressRuleAttachmentResponse, error)
	ListEgressRuleAttachments(context.Context, *ListEgressRuleAttachmentsRequest) (*ListEgressRuleAttachmentsResponse, error)
	// --- Internal ---
	ListEgressRulesByAgent(context.Context, *ListEgressRulesByAgentRequest) (*ListEgressRulesByAgentResponse, error)
	CountRulesReferencingSecret(context.Context, *CountRulesReferencingSecretRequest) (*CountRulesReferencingSecretResponse, error)
}

// UnimplementedEgressRulesServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgressRulesServiceServer struct{}

func (UnimplementedEgressRulesServiceServer) CreateEgressRule(context.Context, *CreateEgressRuleRequest) (*CreateEgressRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEgressRule not implemented")
}
func (UnimplementedEgressRulesServiceServer) GetEgressRule(context.Context, *GetEgressRuleRequest) (*GetEgressRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEgressRule not implemented")
}
func (UnimplementedEgressRulesServiceServer) ListEgressRules(context.Context, *ListEgressRulesRequest) (*ListEgressRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEgressRules not implemented")
}
func (UnimplementedEgressRulesServiceServer) UpdateEgressRule(context.Context, *UpdateEgressRuleRequest) (*UpdateEgressRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEgressRule not implemented")
}
func (UnimplementedEgressRulesServiceServer) DeleteEgressRule(context.Context, *DeleteEgressRuleRequest) (*DeleteEgressRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEgressRule not implemented")
}
func (UnimplementedEgressRulesServiceServer) CreateEgressRuleAttachment(context.Context, *CreateEgressRuleAttachmentRequest) (*CreateEgressRuleAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEgressRuleAttachment not implemented")
}
func (UnimplementedEgressRulesServiceServer) DeleteEgressRuleAttachment(context.Context, *DeleteEgressRuleAttachmentRequest) (*DeleteEgressRuleAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEgressRuleAttachment not implemented")
}
func (UnimplementedEgressRulesServiceServer) ListEgressRuleAttachments(context.Context, *ListEgressRuleAttachmentsRequest) (*ListEgressRuleAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEgressRuleAttachments not implemented")
}
func (UnimplementedEgressRulesServiceServer) ListEgressRulesByAgent(context.Context, *ListEgressRulesByAgentRequest) (*ListEgressRulesByAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEgressRulesByAgent not implemented")
}
func (UnimplementedEgressRulesServiceServer) CountRulesReferencingSecret(context.Context, *CountRulesReferencingSecretRequest) (*CountRulesReferencingSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountRulesReferencingSecret not implemented")
}
func (UnimplementedEgressRulesServiceServer) testEmbeddedByValue() {}

// UnsafeEgressRulesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgressRulesServiceServer will
// result in compilation errors.
type UnsafeEgressRulesServiceServer interface {
	mustEmbedUnimplementedEgressRulesServiceServer()
}

func RegisterEgressRulesServiceServer(s grpc.ServiceRegistrar, srv EgressRulesServiceServer) {
	// If the following call panics, it indicates UnimplementedEgressRulesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EgressRulesService_ServiceDesc, srv)
}

func _EgressRulesService_CreateEgressRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEgressRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).CreateEgressRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_CreateEgressRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).CreateEgressRule(ctx, req.(*CreateEgressRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressRulesService_GetEgressRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEgressRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).GetEgressRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_GetEgressRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).GetEgressRule(ctx, req.(*GetEgressRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressRulesService_ListEgressRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEgressRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).ListEgressRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_ListEgressRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).ListEgressRules(ctx, req.(*ListEgressRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressRulesService_UpdateEgressRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEgressRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).UpdateEgressRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_UpdateEgressRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).UpdateEgressRule(ctx, req.(*UpdateEgressRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressRulesService_DeleteEgressRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEgressRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).DeleteEgressRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_DeleteEgressRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).DeleteEgressRule(ctx, req.(*DeleteEgressRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressRulesService_CreateEgressRuleAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEgressRuleAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).CreateEgressRuleAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_CreateEgressRuleAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).CreateEgressRuleAttachment(ctx, req.(*CreateEgressRuleAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressRulesService_DeleteEgressRuleAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEgressRuleAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).DeleteEgressRuleAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_DeleteEgressRuleAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).DeleteEgressRuleAttachment(ctx, req.(*DeleteEgressRuleAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressRulesService_ListEgressRuleAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEgressRuleAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).ListEgressRuleAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_ListEgressRuleAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).ListEgressRuleAttachments(ctx, req.(*ListEgressRuleAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressRulesService_ListEgressRulesByAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEgressRulesByAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).ListEgressRulesByAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_ListEgressRulesByAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).ListEgressRulesByAgent(ctx, req.(*ListEgressRulesByAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressRulesService_CountRulesReferencingSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRulesReferencingSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressRulesServiceServer).CountRulesReferencingSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressRulesService_CountRulesReferencingSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressRulesServiceServer).CountRulesReferencingSecret(ctx, req.(*CountRulesReferencingSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EgressRulesService_ServiceDesc is the grpc.ServiceDesc for EgressRulesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EgressRulesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.egress.v1.EgressRulesService",
	HandlerType: (*EgressRulesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEgressRule",
			Handler:    _EgressRulesService_CreateEgressRule_Handler,
		},
		{
			MethodName: "GetEgressRule",
			Handler:    _EgressRulesService_GetEgressRule_Handler,
		},
		{
			MethodName: "ListEgressRules",
			Handler:    _EgressRulesService_ListEgressRules_Handler,
		},
		{
			MethodName: "UpdateEgressRule",
			Handler:    _EgressRulesService_UpdateEgressRule_Handler,
		},
		{
			MethodName: "DeleteEgressRule",
			Handler:    _EgressRulesService_DeleteEgressRule_Handler,
		},
		{
			MethodName: "CreateEgressRuleAttachment",
			Handler:    _EgressRulesService_CreateEgressRuleAttachment_Handler,
		},
		{
			MethodName: "DeleteEgressRuleAttachment",
			Handler:    _EgressRulesService_DeleteEgressRuleAttachment_Handler,
		},
		{
			MethodName: "ListEgressRuleAttachments",
			Handler:    _EgressRulesService_ListEgressRuleAttachments_Handler,
		},
		{
			MethodName: "ListEgressRulesByAgent",
			Handler:    _EgressRulesService_ListEgressRulesByAgent_Handler,
		},
		{
			MethodName: "CountRulesReferencingSecret",
			Handler:    _EgressRulesService_CountRulesReferencingSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/egress/v1/egress.proto",
}
