// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/metering/v1/metering.proto

package meteringv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Unit int32

const (
	Unit_UNIT_UNSPECIFIED  Unit = 0
	Unit_UNIT_TOKENS       Unit = 1
	Unit_UNIT_CORE_SECONDS Unit = 2
	Unit_UNIT_GB_SECONDS   Unit = 3
	Unit_UNIT_COUNT        Unit = 4
)

// Enum value maps for Unit.
var (
	Unit_name = map[int32]string{
		0: "UNIT_UNSPECIFIED",
		1: "UNIT_TOKENS",
		2: "UNIT_CORE_SECONDS",
		3: "UNIT_GB_SECONDS",
		4: "UNIT_COUNT",
	}
	Unit_value = map[string]int32{
		"UNIT_UNSPECIFIED":  0,
		"UNIT_TOKENS":       1,
		"UNIT_CORE_SECONDS": 2,
		"UNIT_GB_SECONDS":   3,
		"UNIT_COUNT":        4,
	}
)

func (x Unit) Enum() *Unit {
	p := new(Unit)
	*p = x
	return p
}

func (x Unit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Unit) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_metering_v1_metering_proto_enumTypes[0].Descriptor()
}

func (Unit) Type() protoreflect.EnumType {
	return &file_agynio_api_metering_v1_metering_proto_enumTypes[0]
}

func (x Unit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Unit.Descriptor instead.
func (Unit) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_metering_v1_metering_proto_rawDescGZIP(), []int{0}
}

type Granularity int32

const (
	Granularity_GRANULARITY_UNSPECIFIED  Granularity = 0
	Granularity_GRANULARITY_TOTAL        Granularity = 1
	Granularity_GRANULARITY_DAY          Granularity = 2
	Granularity_GRANULARITY_FIVE_MINUTES Granularity = 3
	Granularity_GRANULARITY_HOUR         Granularity = 4
	Granularity_GRANULARITY_SIX_HOURS    Granularity = 5
)

// Enum value maps for Granularity.
var (
	Granularity_name = map[int32]string{
		0: "GRANULARITY_UNSPECIFIED",
		1: "GRANULARITY_TOTAL",
		2: "GRANULARITY_DAY",
		3: "GRANULARITY_FIVE_MINUTES",
		4: "GRANULARITY_HOUR",
		5: "GRANULARITY_SIX_HOURS",
	}
	Granularity_value = map[string]int32{
		"GRANULARITY_UNSPECIFIED":  0,
		"GRANULARITY_TOTAL":        1,
		"GRANULARITY_DAY":          2,
		"GRANULARITY_FIVE_MINUTES": 3,
		"GRANULARITY_HOUR":         4,
		"GRANULARITY_SIX_HOURS":    5,
	}
)

func (x Granularity) Enum() *Granularity {
	p := new(Granularity)
	*p = x
	return p
}

func (x Granularity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Granularity) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_metering_v1_metering_proto_enumTypes[1].Descriptor()
}

func (Granularity) Type() protoreflect.EnumType {
	return &file_agynio_api_metering_v1_metering_proto_enumTypes[1]
}

func (x Granularity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Granularity.Descriptor instead.
func (Granularity) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_metering_v1_metering_proto_rawDescGZIP(), []int{1}
}

type UsageRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrgId          string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Producer       string                 `protobuf:"bytes,3,opt,name=producer,proto3" json:"producer,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Unit           Unit                   `protobuf:"varint,6,opt,name=unit,proto3,enum=agynio.api.metering.v1.Unit" json:"unit,omitempty"`
	Value          int64                  `protobuf:"varint,7,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsageRecord) Reset() {
	*x = UsageRecord{}
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRecord) ProtoMessage() {}

func (x *UsageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRecord.ProtoReflect.Descriptor instead.
func (*UsageRecord) Descriptor() ([]byte, []int) {
	return file_agynio_api_metering_v1_metering_proto_rawDescGZIP(), []int{0}
}

func (x *UsageRecord) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UsageRecord) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *UsageRecord) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *UsageRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *UsageRecord) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *UsageRecord) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_UNIT_UNSPECIFIED
}

func (x *UsageRecord) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*UsageRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_metering_v1_metering_proto_rawDescGZIP(), []int{1}
}

func (x *RecordRequest) GetRecords() []*UsageRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_metering_v1_metering_proto_rawDescGZIP(), []int{2}
}

type QueryUsageRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	OrgId        string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Start        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Unit         Unit                   `protobuf:"varint,4,opt,name=unit,proto3,enum=agynio.api.metering.v1.Unit" json:"unit,omitempty"`
	LabelFilters map[string]string      `protobuf:"bytes,5,rep,name=label_filters,json=labelFilters,proto3" json:"label_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GroupBy      string                 `protobuf:"bytes,6,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Granularity  Granularity            `protobuf:"varint,7,opt,name=granularity,proto3,enum=agynio.api.metering.v1.Granularity" json:"granularity,omitempty"`
	// IANA time zone ID. Empty defaults to UTC. Applies to bucket alignment for
	// non-total granularities.
	TimeZone      string `protobuf:"bytes,8,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUsageRequest) Reset() {
	*x = QueryUsageRequest{}
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsageRequest) ProtoMessage() {}

func (x *QueryUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsageRequest.ProtoReflect.Descriptor instead.
func (*QueryUsageRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_metering_v1_metering_proto_rawDescGZIP(), []int{3}
}

func (x *QueryUsageRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *QueryUsageRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *QueryUsageRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *QueryUsageRequest) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_UNIT_UNSPECIFIED
}

func (x *QueryUsageRequest) GetLabelFilters() map[string]string {
	if x != nil {
		return x.LabelFilters
	}
	return nil
}

func (x *QueryUsageRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *QueryUsageRequest) GetGranularity() Granularity {
	if x != nil {
		return x.Granularity
	}
	return Granularity_GRANULARITY_UNSPECIFIED
}

func (x *QueryUsageRequest) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

type UsageBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GroupValue    string                 `protobuf:"bytes,2,opt,name=group_value,json=groupValue,proto3" json:"group_value,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageBucket) Reset() {
	*x = UsageBucket{}
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageBucket) ProtoMessage() {}

func (x *UsageBucket) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageBucket.ProtoReflect.Descriptor instead.
func (*UsageBucket) Descriptor() ([]byte, []int) {
	return file_agynio_api_metering_v1_metering_proto_rawDescGZIP(), []int{4}
}

func (x *UsageBucket) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *UsageBucket) GetGroupValue() string {
	if x != nil {
		return x.GroupValue
	}
	return ""
}

func (x *UsageBucket) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type QueryUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*UsageBucket         `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUsageResponse) Reset() {
	*x = QueryUsageResponse{}
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsageResponse) ProtoMessage() {}

func (x *QueryUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_metering_v1_metering_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsageResponse.ProtoReflect.Descriptor instead.
func (*QueryUsageResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_metering_v1_metering_proto_rawDescGZIP(), []int{5}
}

func (x *QueryUsageResponse) GetBuckets() []*UsageBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_agynio_api_metering_v1_metering_proto protoreflect.FileDescriptor

const file_agynio_api_metering_v1_metering_proto_rawDesc = "" +
	"\n" +
	"%agynio/api/metering/v1/metering.proto\x12\x16agynio.api.metering.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x02\n" +
	"\vUsageRecord\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\bproducer\x18\x03 \x01(\tR\bproducer\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12G\n" +
	"\x06labels\x18\x05 \x03(\v2/.agynio.api.metering.v1.UsageRecord.LabelsEntryR\x06labels\x120\n" +
	"\x04unit\x18\x06 \x01(\x0e2\x1c.agynio.api.metering.v1.UnitR\x04unit\x12\x14\n" +
	"\x05value\x18\a \x01(\x03R\x05value\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\rRecordRequest\x12=\n" +
	"\arecords\x18\x01 \x03(\v2#.agynio.api.metering.v1.UsageRecordR\arecords\"\x10\n" +
	"\x0eRecordResponse\"\xde\x03\n" +
	"\x11QueryUsageRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x120\n" +
	"\x04unit\x18\x04 \x01(\x0e2\x1c.agynio.api.metering.v1.UnitR\x04unit\x12`\n" +
	"\rlabel_filters\x18\x05 \x03(\v2;.agynio.api.metering.v1.QueryUsageRequest.LabelFiltersEntryR\flabelFilters\x12\x19\n" +
	"\bgroup_by\x18\x06 \x01(\tR\agroupBy\x12E\n" +
	"\vgranularity\x18\a \x01(\x0e2#.agynio.api.metering.v1.GranularityR\vgranularity\x12\x1b\n" +
	"\ttime_zone\x18\b \x01(\tR\btimeZone\x1a?\n" +
	"\x11LabelFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\vUsageBucket\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vgroup_value\x18\x02 \x01(\tR\n" +
	"groupValue\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\"S\n" +
	"\x12QueryUsageResponse\x12=\n" +
	"\abuckets\x18\x01 \x03(\v2#.agynio.api.metering.v1.UsageBucketR\abuckets*i\n" +
	"\x04Unit\x12\x14\n" +
	"\x10UNIT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vUNIT_TOKENS\x10\x01\x12\x15\n" +
	"\x11UNIT_CORE_SECONDS\x10\x02\x12\x13\n" +
	"\x0fUNIT_GB_SECONDS\x10\x03\x12\x0e\n" +
	"\n" +
	"UNIT_COUNT\x10\x04*\xa5\x01\n" +
	"\vGranularity\x12\x1b\n" +
	"\x17GRANULARITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11GRANULARITY_TOTAL\x10\x01\x12\x13\n" +
	"\x0fGRANULARITY_DAY\x10\x02\x12\x1c\n" +
	"\x18GRANULARITY_FIVE_MINUTES\x10\x03\x12\x14\n" +
	"\x10GRANULARITY_HOUR\x10\x04\x12\x19\n" +
	"\x15GRANULARITY_SIX_HOURS\x10\x052\xcf\x01\n" +
	"\x0fMeteringService\x12W\n" +
	"\x06Record\x12%.agynio.api.metering.v1.RecordRequest\x1a&.agynio.api.metering.v1.RecordResponse\x12c\n" +
	"\n" +
	"QueryUsage\x12).agynio.api.metering.v1.QueryUsageRequest\x1a*.agynio.api.metering.v1.QueryUsageResponseB=Z;github.com/agynio/api/gen/agynio/api/metering/v1;meteringv1b\x06proto3"

var (
	file_agynio_api_metering_v1_metering_proto_rawDescOnce sync.Once
	file_agynio_api_metering_v1_metering_proto_rawDescData []byte
)

func file_agynio_api_metering_v1_metering_proto_rawDescGZIP() []byte {
	file_agynio_api_metering_v1_metering_proto_rawDescOnce.Do(func() {
		file_agynio_api_metering_v1_metering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_metering_v1_metering_proto_rawDesc), len(file_agynio_api_metering_v1_metering_proto_rawDesc)))
	})
	return file_agynio_api_metering_v1_metering_proto_rawDescData
}

var file_agynio_api_metering_v1_metering_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agynio_api_metering_v1_metering_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_agynio_api_metering_v1_metering_proto_goTypes = []any{
	(Unit)(0),                     // 0: agynio.api.metering.v1.Unit
	(Granularity)(0),              // 1: agynio.api.metering.v1.Granularity
	(*UsageRecord)(nil),           // 2: agynio.api.metering.v1.UsageRecord
	(*RecordRequest)(nil),         // 3: agynio.api.metering.v1.RecordRequest
	(*RecordResponse)(nil),        // 4: agynio.api.metering.v1.RecordResponse
	(*QueryUsageRequest)(nil),     // 5: agynio.api.metering.v1.QueryUsageRequest
	(*UsageBucket)(nil),           // 6: agynio.api.metering.v1.UsageBucket
	(*QueryUsageResponse)(nil),    // 7: agynio.api.metering.v1.QueryUsageResponse
	nil,                           // 8: agynio.api.metering.v1.UsageRecord.LabelsEntry
	nil,                           // 9: agynio.api.metering.v1.QueryUsageRequest.LabelFiltersEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_agynio_api_metering_v1_metering_proto_depIdxs = []int32{
	10, // 0: agynio.api.metering.v1.UsageRecord.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 1: agynio.api.metering.v1.UsageRecord.labels:type_name -> agynio.api.metering.v1.UsageRecord.LabelsEntry
	0,  // 2: agynio.api.metering.v1.UsageRecord.unit:type_name -> agynio.api.metering.v1.Unit
	2,  // 3: agynio.api.metering.v1.RecordRequest.records:type_name -> agynio.api.metering.v1.UsageRecord
	10, // 4: agynio.api.metering.v1.QueryUsageRequest.start:type_name -> google.protobuf.Timestamp
	10, // 5: agynio.api.metering.v1.QueryUsageRequest.end:type_name -> google.protobuf.Timestamp
	0,  // 6: agynio.api.metering.v1.QueryUsageRequest.unit:type_name -> agynio.api.metering.v1.Unit
	9,  // 7: agynio.api.metering.v1.QueryUsageRequest.label_filters:type_name -> agynio.api.metering.v1.QueryUsageRequest.LabelFiltersEntry
	1,  // 8: agynio.api.metering.v1.QueryUsageRequest.granularity:type_name -> agynio.api.metering.v1.Granularity
	10, // 9: agynio.api.metering.v1.UsageBucket.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 10: agynio.api.metering.v1.QueryUsageResponse.buckets:type_name -> agynio.api.metering.v1.UsageBucket
	3,  // 11: agynio.api.metering.v1.MeteringService.Record:input_type -> agynio.api.metering.v1.RecordRequest
	5,  // 12: agynio.api.metering.v1.MeteringService.QueryUsage:input_type -> agynio.api.metering.v1.QueryUsageRequest
	4,  // 13: agynio.api.metering.v1.MeteringService.Record:output_type -> agynio.api.metering.v1.RecordResponse
	7,  // 14: agynio.api.metering.v1.MeteringService.QueryUsage:output_type -> agynio.api.metering.v1.QueryUsageResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_agynio_api_metering_v1_metering_proto_init() }
func file_agynio_api_metering_v1_metering_proto_init() {
	if File_agynio_api_metering_v1_metering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_metering_v1_metering_proto_rawDesc), len(file_agynio_api_metering_v1_metering_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_metering_v1_metering_proto_goTypes,
		DependencyIndexes: file_agynio_api_metering_v1_metering_proto_depIdxs,
		EnumInfos:         file_agynio_api_metering_v1_metering_proto_enumTypes,
		MessageInfos:      file_agynio_api_metering_v1_metering_proto_msgTypes,
	}.Build()
	File_agynio_api_metering_v1_metering_proto = out.File
	file_agynio_api_metering_v1_metering_proto_goTypes = nil
	file_agynio_api_metering_v1_metering_proto_depIdxs = nil
}
