// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agynio/api/ziti_management/v1/ziti_management.proto

package zitimanagementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZitiManagementService_CreateAgentIdentity_FullMethodName         = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateAgentIdentity"
	ZitiManagementService_CreateSandboxIdentity_FullMethodName       = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateSandboxIdentity"
	ZitiManagementService_CreateAppIdentity_FullMethodName           = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateAppIdentity"
	ZitiManagementService_CreateService_FullMethodName               = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateService"
	ZitiManagementService_GetService_FullMethodName                  = "/agynio.api.ziti_management.v1.ZitiManagementService/GetService"
	ZitiManagementService_ListServices_FullMethodName                = "/agynio.api.ziti_management.v1.ZitiManagementService/ListServices"
	ZitiManagementService_DeleteIdentity_FullMethodName              = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteIdentity"
	ZitiManagementService_DeleteAppIdentity_FullMethodName           = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteAppIdentity"
	ZitiManagementService_CreateRunnerIdentity_FullMethodName        = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateRunnerIdentity"
	ZitiManagementService_DeleteRunnerIdentity_FullMethodName        = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteRunnerIdentity"
	ZitiManagementService_ListManagedIdentities_FullMethodName       = "/agynio.api.ziti_management.v1.ZitiManagementService/ListManagedIdentities"
	ZitiManagementService_ResolveIdentity_FullMethodName             = "/agynio.api.ziti_management.v1.ZitiManagementService/ResolveIdentity"
	ZitiManagementService_RequestServiceIdentity_FullMethodName      = "/agynio.api.ziti_management.v1.ZitiManagementService/RequestServiceIdentity"
	ZitiManagementService_ExtendIdentityLease_FullMethodName         = "/agynio.api.ziti_management.v1.ZitiManagementService/ExtendIdentityLease"
	ZitiManagementService_CreateServicePolicy_FullMethodName         = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateServicePolicy"
	ZitiManagementService_GetServicePolicy_FullMethodName            = "/agynio.api.ziti_management.v1.ZitiManagementService/GetServicePolicy"
	ZitiManagementService_ListServicePolicies_FullMethodName         = "/agynio.api.ziti_management.v1.ZitiManagementService/ListServicePolicies"
	ZitiManagementService_DeleteServicePolicy_FullMethodName         = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteServicePolicy"
	ZitiManagementService_DeleteService_FullMethodName               = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteService"
	ZitiManagementService_CreateDeviceIdentity_FullMethodName        = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateDeviceIdentity"
	ZitiManagementService_DeleteDeviceIdentity_FullMethodName        = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteDeviceIdentity"
	ZitiManagementService_CreateTunnelIdentity_FullMethodName        = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateTunnelIdentity"
	ZitiManagementService_DeleteTunnelIdentity_FullMethodName        = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteTunnelIdentity"
	ZitiManagementService_PatchIdentityRoleAttributes_FullMethodName = "/agynio.api.ziti_management.v1.ZitiManagementService/PatchIdentityRoleAttributes"
	ZitiManagementService_GetIdentityLiveness_FullMethodName         = "/agynio.api.ziti_management.v1.ZitiManagementService/GetIdentityLiveness"
	ZitiManagementService_ListServicesByTag_FullMethodName           = "/agynio.api.ziti_management.v1.ZitiManagementService/ListServicesByTag"
	ZitiManagementService_ListIdentitiesByTag_FullMethodName         = "/agynio.api.ziti_management.v1.ZitiManagementService/ListIdentitiesByTag"
	ZitiManagementService_ListServicePoliciesByTag_FullMethodName    = "/agynio.api.ziti_management.v1.ZitiManagementService/ListServicePoliciesByTag"
	ZitiManagementService_UpdateService_FullMethodName               = "/agynio.api.ziti_management.v1.ZitiManagementService/UpdateService"
)

// ZitiManagementServiceClient is the client API for ZitiManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZitiManagementServiceClient interface {
	// Orchestrator -> create OpenZiti identity for an agent, return enrollment JWT.
	CreateAgentIdentity(ctx context.Context, in *CreateAgentIdentityRequest, opts ...grpc.CallOption) (*CreateAgentIdentityResponse, error)
	// Orchestrator -> create OpenZiti identity for a sandbox workload, return enrollment JWT.
	CreateSandboxIdentity(ctx context.Context, in *CreateSandboxIdentityRequest, opts ...grpc.CallOption) (*CreateSandboxIdentityResponse, error)
	// Apps Service -> create and enroll an OpenZiti identity for an app. If a previous
	// identity exists, deletes it first. Returns enrolled credentials.
	CreateAppIdentity(ctx context.Context, in *CreateAppIdentityRequest, opts ...grpc.CallOption) (*CreateAppIdentityResponse, error)
	// Runners Service, Apps Service -> create a per-runner or per-app OpenZiti service.
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*CreateServiceResponse, error)
	// Services managing OpenZiti resources -> fetch a service by ID or exact name.
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error)
	// Services managing OpenZiti resources -> list services by name, prefix, role attributes, and pagination.
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// Orchestrator -> delete OpenZiti identity and its platform mapping.
	DeleteIdentity(ctx context.Context, in *DeleteIdentityRequest, opts ...grpc.CallOption) (*DeleteIdentityResponse, error)
	// Apps Service -> delete an app's OpenZiti identity and its associated service.
	// Looked up by platform identity_id.
	DeleteAppIdentity(ctx context.Context, in *DeleteAppIdentityRequest, opts ...grpc.CallOption) (*DeleteAppIdentityResponse, error)
	// Runners Service -> create and enroll an OpenZiti identity for a runner. If a previous
	// identity exists, deletes it first. Returns enrolled credentials.
	CreateRunnerIdentity(ctx context.Context, in *CreateRunnerIdentityRequest, opts ...grpc.CallOption) (*CreateRunnerIdentityResponse, error)
	// Runners Service -> delete a runner's OpenZiti identity and its associated service.
	// Looked up by platform identity_id.
	DeleteRunnerIdentity(ctx context.Context, in *DeleteRunnerIdentityRequest, opts ...grpc.CallOption) (*DeleteRunnerIdentityResponse, error)
	// Orchestrator -> list all platform-managed identities (orphan reconciliation).
	ListManagedIdentities(ctx context.Context, in *ListManagedIdentitiesRequest, opts ...grpc.CallOption) (*ListManagedIdentitiesResponse, error)
	// Gateway -> map OpenZiti identity ID to platform identity (hot path).
	ResolveIdentity(ctx context.Context, in *ResolveIdentityRequest, opts ...grpc.CallOption) (*ResolveIdentityResponse, error)
	// Infrastructure services (Gateway, Orchestrator, Runner) -> request an enrolled
	// OpenZiti identity for the calling service. Ziti Management creates the identity
	// on the Controller, enrolls it (generates key pair, submits CSR, receives cert),
	// and returns the enrolled identity to the caller.
	RequestServiceIdentity(ctx context.Context, in *RequestServiceIdentityRequest, opts ...grpc.CallOption) (*RequestServiceIdentityResponse, error)
	// Infrastructure services -> extend the lease on a service identity.
	// Called periodically by the service to prevent GC from deleting the identity.
	ExtendIdentityLease(ctx context.Context, in *ExtendIdentityLeaseRequest, opts ...grpc.CallOption) (*ExtendIdentityLeaseResponse, error)
	// Expose Service -> create a single OpenZiti service policy (Bind or Dial).
	// Returns the policy ID.
	CreateServicePolicy(ctx context.Context, in *CreateServicePolicyRequest, opts ...grpc.CallOption) (*CreateServicePolicyResponse, error)
	// Services managing OpenZiti resources -> fetch a service policy by ID or exact name.
	GetServicePolicy(ctx context.Context, in *GetServicePolicyRequest, opts ...grpc.CallOption) (*GetServicePolicyResponse, error)
	// Services managing OpenZiti resources -> list service policies by name, prefix, type, roles, and pagination.
	ListServicePolicies(ctx context.Context, in *ListServicePoliciesRequest, opts ...grpc.CallOption) (*ListServicePoliciesResponse, error)
	// Expose Service -> delete an OpenZiti service policy by ID.
	DeleteServicePolicy(ctx context.Context, in *DeleteServicePolicyRequest, opts ...grpc.CallOption) (*DeleteServicePolicyResponse, error)
	// Expose Service -> delete an OpenZiti service by ID.
	// Also deletes attached config objects.
	DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error)
	// Users Service -> create an OpenZiti identity for a user device with
	// roleAttributes: ["devices"] and enrollment.ott: true.
	// Returns the identity ID and enrollment JWT.
	CreateDeviceIdentity(ctx context.Context, in *CreateDeviceIdentityRequest, opts ...grpc.CallOption) (*CreateDeviceIdentityResponse, error)
	// Users Service -> delete a device's OpenZiti identity.
	DeleteDeviceIdentity(ctx context.Context, in *DeleteDeviceIdentityRequest, opts ...grpc.CallOption) (*DeleteDeviceIdentityResponse, error)
	// Networks Service -> create an OpenZiti identity for a private-network tunnel.
	CreateTunnelIdentity(ctx context.Context, in *CreateTunnelIdentityRequest, opts ...grpc.CallOption) (*CreateTunnelIdentityResponse, error)
	// Networks Service -> delete a tunnel's OpenZiti identity.
	DeleteTunnelIdentity(ctx context.Context, in *DeleteTunnelIdentityRequest, opts ...grpc.CallOption) (*DeleteTunnelIdentityResponse, error)
	// Users Service, Apps Service, Agents Orchestrator -> add and remove role attributes.
	PatchIdentityRoleAttributes(ctx context.Context, in *PatchIdentityRoleAttributesRequest, opts ...grpc.CallOption) (*PatchIdentityRoleAttributesResponse, error)
	// Networks Service -> fetch identity enrollment and connectivity state.
	GetIdentityLiveness(ctx context.Context, in *GetIdentityLivenessRequest, opts ...grpc.CallOption) (*GetIdentityLivenessResponse, error)
	// Services managing OpenZiti resources -> list services matching tag filters.
	ListServicesByTag(ctx context.Context, in *ListServicesByTagRequest, opts ...grpc.CallOption) (*ListServicesByTagResponse, error)
	// Networks Service -> list identities matching tag filters.
	ListIdentitiesByTag(ctx context.Context, in *ListIdentitiesByTagRequest, opts ...grpc.CallOption) (*ListIdentitiesByTagResponse, error)
	// Services managing OpenZiti resources -> list service policies matching tag filters.
	ListServicePoliciesByTag(ctx context.Context, in *ListServicePoliciesByTagRequest, opts ...grpc.CallOption) (*ListServicePoliciesByTagResponse, error)
	// Networks Service -> update an existing OpenZiti service's attached configs.
	UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*UpdateServiceResponse, error)
}

type zitiManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZitiManagementServiceClient(cc grpc.ClientConnInterface) ZitiManagementServiceClient {
	return &zitiManagementServiceClient{cc}
}

func (c *zitiManagementServiceClient) CreateAgentIdentity(ctx context.Context, in *CreateAgentIdentityRequest, opts ...grpc.CallOption) (*CreateAgentIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_CreateAgentIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) CreateSandboxIdentity(ctx context.Context, in *CreateSandboxIdentityRequest, opts ...grpc.CallOption) (*CreateSandboxIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_CreateSandboxIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) CreateAppIdentity(ctx context.Context, in *CreateAppIdentityRequest, opts ...grpc.CallOption) (*CreateAppIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAppIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_CreateAppIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*CreateServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServiceResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) DeleteIdentity(ctx context.Context, in *DeleteIdentityRequest, opts ...grpc.CallOption) (*DeleteIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_DeleteIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) DeleteAppIdentity(ctx context.Context, in *DeleteAppIdentityRequest, opts ...grpc.CallOption) (*DeleteAppIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAppIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_DeleteAppIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) CreateRunnerIdentity(ctx context.Context, in *CreateRunnerIdentityRequest, opts ...grpc.CallOption) (*CreateRunnerIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRunnerIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_CreateRunnerIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) DeleteRunnerIdentity(ctx context.Context, in *DeleteRunnerIdentityRequest, opts ...grpc.CallOption) (*DeleteRunnerIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRunnerIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_DeleteRunnerIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ListManagedIdentities(ctx context.Context, in *ListManagedIdentitiesRequest, opts ...grpc.CallOption) (*ListManagedIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManagedIdentitiesResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ListManagedIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ResolveIdentity(ctx context.Context, in *ResolveIdentityRequest, opts ...grpc.CallOption) (*ResolveIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ResolveIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) RequestServiceIdentity(ctx context.Context, in *RequestServiceIdentityRequest, opts ...grpc.CallOption) (*RequestServiceIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestServiceIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_RequestServiceIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ExtendIdentityLease(ctx context.Context, in *ExtendIdentityLeaseRequest, opts ...grpc.CallOption) (*ExtendIdentityLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendIdentityLeaseResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ExtendIdentityLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) CreateServicePolicy(ctx context.Context, in *CreateServicePolicyRequest, opts ...grpc.CallOption) (*CreateServicePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServicePolicyResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_CreateServicePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) GetServicePolicy(ctx context.Context, in *GetServicePolicyRequest, opts ...grpc.CallOption) (*GetServicePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServicePolicyResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_GetServicePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ListServicePolicies(ctx context.Context, in *ListServicePoliciesRequest, opts ...grpc.CallOption) (*ListServicePoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicePoliciesResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ListServicePolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) DeleteServicePolicy(ctx context.Context, in *DeleteServicePolicyRequest, opts ...grpc.CallOption) (*DeleteServicePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServicePolicyResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_DeleteServicePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServiceResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_DeleteService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) CreateDeviceIdentity(ctx context.Context, in *CreateDeviceIdentityRequest, opts ...grpc.CallOption) (*CreateDeviceIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeviceIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_CreateDeviceIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) DeleteDeviceIdentity(ctx context.Context, in *DeleteDeviceIdentityRequest, opts ...grpc.CallOption) (*DeleteDeviceIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeviceIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_DeleteDeviceIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) CreateTunnelIdentity(ctx context.Context, in *CreateTunnelIdentityRequest, opts ...grpc.CallOption) (*CreateTunnelIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTunnelIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_CreateTunnelIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) DeleteTunnelIdentity(ctx context.Context, in *DeleteTunnelIdentityRequest, opts ...grpc.CallOption) (*DeleteTunnelIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTunnelIdentityResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_DeleteTunnelIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) PatchIdentityRoleAttributes(ctx context.Context, in *PatchIdentityRoleAttributesRequest, opts ...grpc.CallOption) (*PatchIdentityRoleAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchIdentityRoleAttributesResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_PatchIdentityRoleAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) GetIdentityLiveness(ctx context.Context, in *GetIdentityLivenessRequest, opts ...grpc.CallOption) (*GetIdentityLivenessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdentityLivenessResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_GetIdentityLiveness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ListServicesByTag(ctx context.Context, in *ListServicesByTagRequest, opts ...grpc.CallOption) (*ListServicesByTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesByTagResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ListServicesByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ListIdentitiesByTag(ctx context.Context, in *ListIdentitiesByTagRequest, opts ...grpc.CallOption) (*ListIdentitiesByTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdentitiesByTagResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ListIdentitiesByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) ListServicePoliciesByTag(ctx context.Context, in *ListServicePoliciesByTagRequest, opts ...grpc.CallOption) (*ListServicePoliciesByTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicePoliciesByTagResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_ListServicePoliciesByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zitiManagementServiceClient) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*UpdateServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServiceResponse)
	err := c.cc.Invoke(ctx, ZitiManagementService_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZitiManagementServiceServer is the server API for ZitiManagementService service.
// All implementations should embed UnimplementedZitiManagementServiceServer
// for forward compatibility.
type ZitiManagementServiceServer interface {
	// Orchestrator -> create OpenZiti identity for an agent, return enrollment JWT.
	CreateAgentIdentity(context.Context, *CreateAgentIdentityRequest) (*CreateAgentIdentityResponse, error)
	// Orchestrator -> create OpenZiti identity for a sandbox workload, return enrollment JWT.
	CreateSandboxIdentity(context.Context, *CreateSandboxIdentityRequest) (*CreateSandboxIdentityResponse, error)
	// Apps Service -> create and enroll an OpenZiti identity for an app. If a previous
	// identity exists, deletes it first. Returns enrolled credentials.
	CreateAppIdentity(context.Context, *CreateAppIdentityRequest) (*CreateAppIdentityResponse, error)
	// Runners Service, Apps Service -> create a per-runner or per-app OpenZiti service.
	CreateService(context.Context, *CreateServiceRequest) (*CreateServiceResponse, error)
	// Services managing OpenZiti resources -> fetch a service by ID or exact name.
	GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error)
	// Services managing OpenZiti resources -> list services by name, prefix, role attributes, and pagination.
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// Orchestrator -> delete OpenZiti identity and its platform mapping.
	DeleteIdentity(context.Context, *DeleteIdentityRequest) (*DeleteIdentityResponse, error)
	// Apps Service -> delete an app's OpenZiti identity and its associated service.
	// Looked up by platform identity_id.
	DeleteAppIdentity(context.Context, *DeleteAppIdentityRequest) (*DeleteAppIdentityResponse, error)
	// Runners Service -> create and enroll an OpenZiti identity for a runner. If a previous
	// identity exists, deletes it first. Returns enrolled credentials.
	CreateRunnerIdentity(context.Context, *CreateRunnerIdentityRequest) (*CreateRunnerIdentityResponse, error)
	// Runners Service -> delete a runner's OpenZiti identity and its associated service.
	// Looked up by platform identity_id.
	DeleteRunnerIdentity(context.Context, *DeleteRunnerIdentityRequest) (*DeleteRunnerIdentityResponse, error)
	// Orchestrator -> list all platform-managed identities (orphan reconciliation).
	ListManagedIdentities(context.Context, *ListManagedIdentitiesRequest) (*ListManagedIdentitiesResponse, error)
	// Gateway -> map OpenZiti identity ID to platform identity (hot path).
	ResolveIdentity(context.Context, *ResolveIdentityRequest) (*ResolveIdentityResponse, error)
	// Infrastructure services (Gateway, Orchestrator, Runner) -> request an enrolled
	// OpenZiti identity for the calling service. Ziti Management creates the identity
	// on the Controller, enrolls it (generates key pair, submits CSR, receives cert),
	// and returns the enrolled identity to the caller.
	RequestServiceIdentity(context.Context, *RequestServiceIdentityRequest) (*RequestServiceIdentityResponse, error)
	// Infrastructure services -> extend the lease on a service identity.
	// Called periodically by the service to prevent GC from deleting the identity.
	ExtendIdentityLease(context.Context, *ExtendIdentityLeaseRequest) (*ExtendIdentityLeaseResponse, error)
	// Expose Service -> create a single OpenZiti service policy (Bind or Dial).
	// Returns the policy ID.
	CreateServicePolicy(context.Context, *CreateServicePolicyRequest) (*CreateServicePolicyResponse, error)
	// Services managing OpenZiti resources -> fetch a service policy by ID or exact name.
	GetServicePolicy(context.Context, *GetServicePolicyRequest) (*GetServicePolicyResponse, error)
	// Services managing OpenZiti resources -> list service policies by name, prefix, type, roles, and pagination.
	ListServicePolicies(context.Context, *ListServicePoliciesRequest) (*ListServicePoliciesResponse, error)
	// Expose Service -> delete an OpenZiti service policy by ID.
	DeleteServicePolicy(context.Context, *DeleteServicePolicyRequest) (*DeleteServicePolicyResponse, error)
	// Expose Service -> delete an OpenZiti service by ID.
	// Also deletes attached config objects.
	DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error)
	// Users Service -> create an OpenZiti identity for a user device with
	// roleAttributes: ["devices"] and enrollment.ott: true.
	// Returns the identity ID and enrollment JWT.
	CreateDeviceIdentity(context.Context, *CreateDeviceIdentityRequest) (*CreateDeviceIdentityResponse, error)
	// Users Service -> delete a device's OpenZiti identity.
	DeleteDeviceIdentity(context.Context, *DeleteDeviceIdentityRequest) (*DeleteDeviceIdentityResponse, error)
	// Networks Service -> create an OpenZiti identity for a private-network tunnel.
	CreateTunnelIdentity(context.Context, *CreateTunnelIdentityRequest) (*CreateTunnelIdentityResponse, error)
	// Networks Service -> delete a tunnel's OpenZiti identity.
	DeleteTunnelIdentity(context.Context, *DeleteTunnelIdentityRequest) (*DeleteTunnelIdentityResponse, error)
	// Users Service, Apps Service, Agents Orchestrator -> add and remove role attributes.
	PatchIdentityRoleAttributes(context.Context, *PatchIdentityRoleAttributesRequest) (*PatchIdentityRoleAttributesResponse, error)
	// Networks Service -> fetch identity enrollment and connectivity state.
	GetIdentityLiveness(context.Context, *GetIdentityLivenessRequest) (*GetIdentityLivenessResponse, error)
	// Services managing OpenZiti resources -> list services matching tag filters.
	ListServicesByTag(context.Context, *ListServicesByTagRequest) (*ListServicesByTagResponse, error)
	// Networks Service -> list identities matching tag filters.
	ListIdentitiesByTag(context.Context, *ListIdentitiesByTagRequest) (*ListIdentitiesByTagResponse, error)
	// Services managing OpenZiti resources -> list service policies matching tag filters.
	ListServicePoliciesByTag(context.Context, *ListServicePoliciesByTagRequest) (*ListServicePoliciesByTagResponse, error)
	// Networks Service -> update an existing OpenZiti service's attached configs.
	UpdateService(context.Context, *UpdateServiceRequest) (*UpdateServiceResponse, error)
}

// UnimplementedZitiManagementServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZitiManagementServiceServer struct{}

func (UnimplementedZitiManagementServiceServer) CreateAgentIdentity(context.Context, *CreateAgentIdentityRequest) (*CreateAgentIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgentIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) CreateSandboxIdentity(context.Context, *CreateSandboxIdentityRequest) (*CreateSandboxIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandboxIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) CreateAppIdentity(context.Context, *CreateAppIdentityRequest) (*CreateAppIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAppIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) CreateService(context.Context, *CreateServiceRequest) (*CreateServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedZitiManagementServiceServer) GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedZitiManagementServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedZitiManagementServiceServer) DeleteIdentity(context.Context, *DeleteIdentityRequest) (*DeleteIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) DeleteAppIdentity(context.Context, *DeleteAppIdentityRequest) (*DeleteAppIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAppIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) CreateRunnerIdentity(context.Context, *CreateRunnerIdentityRequest) (*CreateRunnerIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRunnerIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) DeleteRunnerIdentity(context.Context, *DeleteRunnerIdentityRequest) (*DeleteRunnerIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRunnerIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) ListManagedIdentities(context.Context, *ListManagedIdentitiesRequest) (*ListManagedIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManagedIdentities not implemented")
}
func (UnimplementedZitiManagementServiceServer) ResolveIdentity(context.Context, *ResolveIdentityRequest) (*ResolveIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) RequestServiceIdentity(context.Context, *RequestServiceIdentityRequest) (*RequestServiceIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestServiceIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) ExtendIdentityLease(context.Context, *ExtendIdentityLeaseRequest) (*ExtendIdentityLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendIdentityLease not implemented")
}
func (UnimplementedZitiManagementServiceServer) CreateServicePolicy(context.Context, *CreateServicePolicyRequest) (*CreateServicePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServicePolicy not implemented")
}
func (UnimplementedZitiManagementServiceServer) GetServicePolicy(context.Context, *GetServicePolicyRequest) (*GetServicePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServicePolicy not implemented")
}
func (UnimplementedZitiManagementServiceServer) ListServicePolicies(context.Context, *ListServicePoliciesRequest) (*ListServicePoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServicePolicies not implemented")
}
func (UnimplementedZitiManagementServiceServer) DeleteServicePolicy(context.Context, *DeleteServicePolicyRequest) (*DeleteServicePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteServicePolicy not implemented")
}
func (UnimplementedZitiManagementServiceServer) DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedZitiManagementServiceServer) CreateDeviceIdentity(context.Context, *CreateDeviceIdentityRequest) (*CreateDeviceIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDeviceIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) DeleteDeviceIdentity(context.Context, *DeleteDeviceIdentityRequest) (*DeleteDeviceIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDeviceIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) CreateTunnelIdentity(context.Context, *CreateTunnelIdentityRequest) (*CreateTunnelIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTunnelIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) DeleteTunnelIdentity(context.Context, *DeleteTunnelIdentityRequest) (*DeleteTunnelIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTunnelIdentity not implemented")
}
func (UnimplementedZitiManagementServiceServer) PatchIdentityRoleAttributes(context.Context, *PatchIdentityRoleAttributesRequest) (*PatchIdentityRoleAttributesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchIdentityRoleAttributes not implemented")
}
func (UnimplementedZitiManagementServiceServer) GetIdentityLiveness(context.Context, *GetIdentityLivenessRequest) (*GetIdentityLivenessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentityLiveness not implemented")
}
func (UnimplementedZitiManagementServiceServer) ListServicesByTag(context.Context, *ListServicesByTagRequest) (*ListServicesByTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServicesByTag not implemented")
}
func (UnimplementedZitiManagementServiceServer) ListIdentitiesByTag(context.Context, *ListIdentitiesByTagRequest) (*ListIdentitiesByTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdentitiesByTag not implemented")
}
func (UnimplementedZitiManagementServiceServer) ListServicePoliciesByTag(context.Context, *ListServicePoliciesByTagRequest) (*ListServicePoliciesByTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServicePoliciesByTag not implemented")
}
func (UnimplementedZitiManagementServiceServer) UpdateService(context.Context, *UpdateServiceRequest) (*UpdateServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedZitiManagementServiceServer) testEmbeddedByValue() {}

// UnsafeZitiManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZitiManagementServiceServer will
// result in compilation errors.
type UnsafeZitiManagementServiceServer interface {
	mustEmbedUnimplementedZitiManagementServiceServer()
}

func RegisterZitiManagementServiceServer(s grpc.ServiceRegistrar, srv ZitiManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedZitiManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZitiManagementService_ServiceDesc, srv)
}

func _ZitiManagementService_CreateAgentIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).CreateAgentIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_CreateAgentIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).CreateAgentIdentity(ctx, req.(*CreateAgentIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_CreateSandboxIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).CreateSandboxIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_CreateSandboxIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).CreateSandboxIdentity(ctx, req.(*CreateSandboxIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_CreateAppIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).CreateAppIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_CreateAppIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).CreateAppIdentity(ctx, req.(*CreateAppIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_DeleteIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).DeleteIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_DeleteIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).DeleteIdentity(ctx, req.(*DeleteIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_DeleteAppIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).DeleteAppIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_DeleteAppIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).DeleteAppIdentity(ctx, req.(*DeleteAppIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_CreateRunnerIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRunnerIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).CreateRunnerIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_CreateRunnerIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).CreateRunnerIdentity(ctx, req.(*CreateRunnerIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_DeleteRunnerIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRunnerIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).DeleteRunnerIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_DeleteRunnerIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).DeleteRunnerIdentity(ctx, req.(*DeleteRunnerIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ListManagedIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManagedIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ListManagedIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ListManagedIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ListManagedIdentities(ctx, req.(*ListManagedIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ResolveIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ResolveIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ResolveIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ResolveIdentity(ctx, req.(*ResolveIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_RequestServiceIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestServiceIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).RequestServiceIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_RequestServiceIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).RequestServiceIdentity(ctx, req.(*RequestServiceIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ExtendIdentityLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendIdentityLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ExtendIdentityLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ExtendIdentityLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ExtendIdentityLease(ctx, req.(*ExtendIdentityLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_CreateServicePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServicePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).CreateServicePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_CreateServicePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).CreateServicePolicy(ctx, req.(*CreateServicePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_GetServicePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServicePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).GetServicePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_GetServicePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).GetServicePolicy(ctx, req.(*GetServicePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ListServicePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicePoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ListServicePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ListServicePolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ListServicePolicies(ctx, req.(*ListServicePoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_DeleteServicePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServicePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).DeleteServicePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_DeleteServicePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).DeleteServicePolicy(ctx, req.(*DeleteServicePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).DeleteService(ctx, req.(*DeleteServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_CreateDeviceIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).CreateDeviceIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_CreateDeviceIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).CreateDeviceIdentity(ctx, req.(*CreateDeviceIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_DeleteDeviceIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).DeleteDeviceIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_DeleteDeviceIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).DeleteDeviceIdentity(ctx, req.(*DeleteDeviceIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_CreateTunnelIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTunnelIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).CreateTunnelIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_CreateTunnelIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).CreateTunnelIdentity(ctx, req.(*CreateTunnelIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_DeleteTunnelIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTunnelIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).DeleteTunnelIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_DeleteTunnelIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).DeleteTunnelIdentity(ctx, req.(*DeleteTunnelIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_PatchIdentityRoleAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchIdentityRoleAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).PatchIdentityRoleAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_PatchIdentityRoleAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).PatchIdentityRoleAttributes(ctx, req.(*PatchIdentityRoleAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_GetIdentityLiveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityLivenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).GetIdentityLiveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_GetIdentityLiveness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).GetIdentityLiveness(ctx, req.(*GetIdentityLivenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ListServicesByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ListServicesByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ListServicesByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ListServicesByTag(ctx, req.(*ListServicesByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ListIdentitiesByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentitiesByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ListIdentitiesByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ListIdentitiesByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ListIdentitiesByTag(ctx, req.(*ListIdentitiesByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_ListServicePoliciesByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicePoliciesByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).ListServicePoliciesByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_ListServicePoliciesByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).ListServicePoliciesByTag(ctx, req.(*ListServicePoliciesByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZitiManagementService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZitiManagementServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZitiManagementService_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZitiManagementServiceServer).UpdateService(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZitiManagementService_ServiceDesc is the grpc.ServiceDesc for ZitiManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZitiManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.ziti_management.v1.ZitiManagementService",
	HandlerType: (*ZitiManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgentIdentity",
			Handler:    _ZitiManagementService_CreateAgentIdentity_Handler,
		},
		{
			MethodName: "CreateSandboxIdentity",
			Handler:    _ZitiManagementService_CreateSandboxIdentity_Handler,
		},
		{
			MethodName: "CreateAppIdentity",
			Handler:    _ZitiManagementService_CreateAppIdentity_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _ZitiManagementService_CreateService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _ZitiManagementService_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ZitiManagementService_ListServices_Handler,
		},
		{
			MethodName: "DeleteIdentity",
			Handler:    _ZitiManagementService_DeleteIdentity_Handler,
		},
		{
			MethodName: "DeleteAppIdentity",
			Handler:    _ZitiManagementService_DeleteAppIdentity_Handler,
		},
		{
			MethodName: "CreateRunnerIdentity",
			Handler:    _ZitiManagementService_CreateRunnerIdentity_Handler,
		},
		{
			MethodName: "DeleteRunnerIdentity",
			Handler:    _ZitiManagementService_DeleteRunnerIdentity_Handler,
		},
		{
			MethodName: "ListManagedIdentities",
			Handler:    _ZitiManagementService_ListManagedIdentities_Handler,
		},
		{
			MethodName: "ResolveIdentity",
			Handler:    _ZitiManagementService_ResolveIdentity_Handler,
		},
		{
			MethodName: "RequestServiceIdentity",
			Handler:    _ZitiManagementService_RequestServiceIdentity_Handler,
		},
		{
			MethodName: "ExtendIdentityLease",
			Handler:    _ZitiManagementService_ExtendIdentityLease_Handler,
		},
		{
			MethodName: "CreateServicePolicy",
			Handler:    _ZitiManagementService_CreateServicePolicy_Handler,
		},
		{
			MethodName: "GetServicePolicy",
			Handler:    _ZitiManagementService_GetServicePolicy_Handler,
		},
		{
			MethodName: "ListServicePolicies",
			Handler:    _ZitiManagementService_ListServicePolicies_Handler,
		},
		{
			MethodName: "DeleteServicePolicy",
			Handler:    _ZitiManagementService_DeleteServicePolicy_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _ZitiManagementService_DeleteService_Handler,
		},
		{
			MethodName: "CreateDeviceIdentity",
			Handler:    _ZitiManagementService_CreateDeviceIdentity_Handler,
		},
		{
			MethodName: "DeleteDeviceIdentity",
			Handler:    _ZitiManagementService_DeleteDeviceIdentity_Handler,
		},
		{
			MethodName: "CreateTunnelIdentity",
			Handler:    _ZitiManagementService_CreateTunnelIdentity_Handler,
		},
		{
			MethodName: "DeleteTunnelIdentity",
			Handler:    _ZitiManagementService_DeleteTunnelIdentity_Handler,
		},
		{
			MethodName: "PatchIdentityRoleAttributes",
			Handler:    _ZitiManagementService_PatchIdentityRoleAttributes_Handler,
		},
		{
			MethodName: "GetIdentityLiveness",
			Handler:    _ZitiManagementService_GetIdentityLiveness_Handler,
		},
		{
			MethodName: "ListServicesByTag",
			Handler:    _ZitiManagementService_ListServicesByTag_Handler,
		},
		{
			MethodName: "ListIdentitiesByTag",
			Handler:    _ZitiManagementService_ListIdentitiesByTag_Handler,
		},
		{
			MethodName: "ListServicePoliciesByTag",
			Handler:    _ZitiManagementService_ListServicePoliciesByTag_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _ZitiManagementService_UpdateService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/ziti_management/v1/ziti_management.proto",
}
