// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: agynio/api/secrets/v1/secrets.proto

package secretsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretsService_CreateSecretProvider_FullMethodName   = "/agynio.api.secrets.v1.SecretsService/CreateSecretProvider"
	SecretsService_GetSecretProvider_FullMethodName      = "/agynio.api.secrets.v1.SecretsService/GetSecretProvider"
	SecretsService_UpdateSecretProvider_FullMethodName   = "/agynio.api.secrets.v1.SecretsService/UpdateSecretProvider"
	SecretsService_DeleteSecretProvider_FullMethodName   = "/agynio.api.secrets.v1.SecretsService/DeleteSecretProvider"
	SecretsService_ListSecretProviders_FullMethodName    = "/agynio.api.secrets.v1.SecretsService/ListSecretProviders"
	SecretsService_CreateSecret_FullMethodName           = "/agynio.api.secrets.v1.SecretsService/CreateSecret"
	SecretsService_GetSecret_FullMethodName              = "/agynio.api.secrets.v1.SecretsService/GetSecret"
	SecretsService_UpdateSecret_FullMethodName           = "/agynio.api.secrets.v1.SecretsService/UpdateSecret"
	SecretsService_DeleteSecret_FullMethodName           = "/agynio.api.secrets.v1.SecretsService/DeleteSecret"
	SecretsService_ListSecrets_FullMethodName            = "/agynio.api.secrets.v1.SecretsService/ListSecrets"
	SecretsService_ResolveSecret_FullMethodName          = "/agynio.api.secrets.v1.SecretsService/ResolveSecret"
	SecretsService_ResolveSecretExists_FullMethodName    = "/agynio.api.secrets.v1.SecretsService/ResolveSecretExists"
	SecretsService_CreateImagePullSecret_FullMethodName  = "/agynio.api.secrets.v1.SecretsService/CreateImagePullSecret"
	SecretsService_GetImagePullSecret_FullMethodName     = "/agynio.api.secrets.v1.SecretsService/GetImagePullSecret"
	SecretsService_UpdateImagePullSecret_FullMethodName  = "/agynio.api.secrets.v1.SecretsService/UpdateImagePullSecret"
	SecretsService_DeleteImagePullSecret_FullMethodName  = "/agynio.api.secrets.v1.SecretsService/DeleteImagePullSecret"
	SecretsService_ListImagePullSecrets_FullMethodName   = "/agynio.api.secrets.v1.SecretsService/ListImagePullSecrets"
	SecretsService_ResolveImagePullSecret_FullMethodName = "/agynio.api.secrets.v1.SecretsService/ResolveImagePullSecret"
)

// SecretsServiceClient is the client API for SecretsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretsService manages secret providers and secrets.
//
// Secret providers represent connections to external secret management systems
// (e.g. HashiCorp Vault). Secrets are internal references to values stored in
// those external systems. The service never persists secret values - it resolves
// them on demand via the ResolveSecret RPC.
type SecretsServiceClient interface {
	// --- Secret Providers ---
	CreateSecretProvider(ctx context.Context, in *CreateSecretProviderRequest, opts ...grpc.CallOption) (*CreateSecretProviderResponse, error)
	GetSecretProvider(ctx context.Context, in *GetSecretProviderRequest, opts ...grpc.CallOption) (*GetSecretProviderResponse, error)
	UpdateSecretProvider(ctx context.Context, in *UpdateSecretProviderRequest, opts ...grpc.CallOption) (*UpdateSecretProviderResponse, error)
	DeleteSecretProvider(ctx context.Context, in *DeleteSecretProviderRequest, opts ...grpc.CallOption) (*DeleteSecretProviderResponse, error)
	ListSecretProviders(ctx context.Context, in *ListSecretProvidersRequest, opts ...grpc.CallOption) (*ListSecretProvidersResponse, error)
	// --- Secrets ---
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error)
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error)
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error)
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
	// --- Resolution ---
	// Resolve a secret to its actual value by fetching from the external provider.
	ResolveSecret(ctx context.Context, in *ResolveSecretRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error)
	// Verify that a secret exists without resolving its value.
	ResolveSecretExists(ctx context.Context, in *ResolveSecretExistsRequest, opts ...grpc.CallOption) (*ResolveSecretExistsResponse, error)
	// --- Image Pull Secrets ---
	CreateImagePullSecret(ctx context.Context, in *CreateImagePullSecretRequest, opts ...grpc.CallOption) (*CreateImagePullSecretResponse, error)
	GetImagePullSecret(ctx context.Context, in *GetImagePullSecretRequest, opts ...grpc.CallOption) (*GetImagePullSecretResponse, error)
	UpdateImagePullSecret(ctx context.Context, in *UpdateImagePullSecretRequest, opts ...grpc.CallOption) (*UpdateImagePullSecretResponse, error)
	DeleteImagePullSecret(ctx context.Context, in *DeleteImagePullSecretRequest, opts ...grpc.CallOption) (*DeleteImagePullSecretResponse, error)
	ListImagePullSecrets(ctx context.Context, in *ListImagePullSecretsRequest, opts ...grpc.CallOption) (*ListImagePullSecretsResponse, error)
	// --- Image Pull Secret Resolution ---
	ResolveImagePullSecret(ctx context.Context, in *ResolveImagePullSecretRequest, opts ...grpc.CallOption) (*ResolveImagePullSecretResponse, error)
}

type secretsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsServiceClient(cc grpc.ClientConnInterface) SecretsServiceClient {
	return &secretsServiceClient{cc}
}

func (c *secretsServiceClient) CreateSecretProvider(ctx context.Context, in *CreateSecretProviderRequest, opts ...grpc.CallOption) (*CreateSecretProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecretProviderResponse)
	err := c.cc.Invoke(ctx, SecretsService_CreateSecretProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) GetSecretProvider(ctx context.Context, in *GetSecretProviderRequest, opts ...grpc.CallOption) (*GetSecretProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretProviderResponse)
	err := c.cc.Invoke(ctx, SecretsService_GetSecretProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) UpdateSecretProvider(ctx context.Context, in *UpdateSecretProviderRequest, opts ...grpc.CallOption) (*UpdateSecretProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSecretProviderResponse)
	err := c.cc.Invoke(ctx, SecretsService_UpdateSecretProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) DeleteSecretProvider(ctx context.Context, in *DeleteSecretProviderRequest, opts ...grpc.CallOption) (*DeleteSecretProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretProviderResponse)
	err := c.cc.Invoke(ctx, SecretsService_DeleteSecretProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ListSecretProviders(ctx context.Context, in *ListSecretProvidersRequest, opts ...grpc.CallOption) (*ListSecretProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretProvidersResponse)
	err := c.cc.Invoke(ctx, SecretsService_ListSecretProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_UpdateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, SecretsService_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ResolveSecret(ctx context.Context, in *ResolveSecretRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_ResolveSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ResolveSecretExists(ctx context.Context, in *ResolveSecretExistsRequest, opts ...grpc.CallOption) (*ResolveSecretExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSecretExistsResponse)
	err := c.cc.Invoke(ctx, SecretsService_ResolveSecretExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) CreateImagePullSecret(ctx context.Context, in *CreateImagePullSecretRequest, opts ...grpc.CallOption) (*CreateImagePullSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateImagePullSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_CreateImagePullSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) GetImagePullSecret(ctx context.Context, in *GetImagePullSecretRequest, opts ...grpc.CallOption) (*GetImagePullSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImagePullSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_GetImagePullSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) UpdateImagePullSecret(ctx context.Context, in *UpdateImagePullSecretRequest, opts ...grpc.CallOption) (*UpdateImagePullSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateImagePullSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_UpdateImagePullSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) DeleteImagePullSecret(ctx context.Context, in *DeleteImagePullSecretRequest, opts ...grpc.CallOption) (*DeleteImagePullSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteImagePullSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_DeleteImagePullSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ListImagePullSecrets(ctx context.Context, in *ListImagePullSecretsRequest, opts ...grpc.CallOption) (*ListImagePullSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagePullSecretsResponse)
	err := c.cc.Invoke(ctx, SecretsService_ListImagePullSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ResolveImagePullSecret(ctx context.Context, in *ResolveImagePullSecretRequest, opts ...grpc.CallOption) (*ResolveImagePullSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveImagePullSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_ResolveImagePullSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsServiceServer is the server API for SecretsService service.
// All implementations should embed UnimplementedSecretsServiceServer
// for forward compatibility.
//
// SecretsService manages secret providers and secrets.
//
// Secret providers represent connections to external secret management systems
// (e.g. HashiCorp Vault). Secrets are internal references to values stored in
// those external systems. The service never persists secret values - it resolves
// them on demand via the ResolveSecret RPC.
type SecretsServiceServer interface {
	// --- Secret Providers ---
	CreateSecretProvider(context.Context, *CreateSecretProviderRequest) (*CreateSecretProviderResponse, error)
	GetSecretProvider(context.Context, *GetSecretProviderRequest) (*GetSecretProviderResponse, error)
	UpdateSecretProvider(context.Context, *UpdateSecretProviderRequest) (*UpdateSecretProviderResponse, error)
	DeleteSecretProvider(context.Context, *DeleteSecretProviderRequest) (*DeleteSecretProviderResponse, error)
	ListSecretProviders(context.Context, *ListSecretProvidersRequest) (*ListSecretProvidersResponse, error)
	// --- Secrets ---
	CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error)
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	UpdateSecret(context.Context, *UpdateSecretRequest) (*UpdateSecretResponse, error)
	DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error)
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	// --- Resolution ---
	// Resolve a secret to its actual value by fetching from the external provider.
	ResolveSecret(context.Context, *ResolveSecretRequest) (*ResolveSecretResponse, error)
	// Verify that a secret exists without resolving its value.
	ResolveSecretExists(context.Context, *ResolveSecretExistsRequest) (*ResolveSecretExistsResponse, error)
	// --- Image Pull Secrets ---
	CreateImagePullSecret(context.Context, *CreateImagePullSecretRequest) (*CreateImagePullSecretResponse, error)
	GetImagePullSecret(context.Context, *GetImagePullSecretRequest) (*GetImagePullSecretResponse, error)
	UpdateImagePullSecret(context.Context, *UpdateImagePullSecretRequest) (*UpdateImagePullSecretResponse, error)
	DeleteImagePullSecret(context.Context, *DeleteImagePullSecretRequest) (*DeleteImagePullSecretResponse, error)
	ListImagePullSecrets(context.Context, *ListImagePullSecretsRequest) (*ListImagePullSecretsResponse, error)
	// --- Image Pull Secret Resolution ---
	ResolveImagePullSecret(context.Context, *ResolveImagePullSecretRequest) (*ResolveImagePullSecretResponse, error)
}

// UnimplementedSecretsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsServiceServer struct{}

func (UnimplementedSecretsServiceServer) CreateSecretProvider(context.Context, *CreateSecretProviderRequest) (*CreateSecretProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecretProvider not implemented")
}
func (UnimplementedSecretsServiceServer) GetSecretProvider(context.Context, *GetSecretProviderRequest) (*GetSecretProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecretProvider not implemented")
}
func (UnimplementedSecretsServiceServer) UpdateSecretProvider(context.Context, *UpdateSecretProviderRequest) (*UpdateSecretProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecretProvider not implemented")
}
func (UnimplementedSecretsServiceServer) DeleteSecretProvider(context.Context, *DeleteSecretProviderRequest) (*DeleteSecretProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecretProvider not implemented")
}
func (UnimplementedSecretsServiceServer) ListSecretProviders(context.Context, *ListSecretProvidersRequest) (*ListSecretProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecretProviders not implemented")
}
func (UnimplementedSecretsServiceServer) CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedSecretsServiceServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedSecretsServiceServer) UpdateSecret(context.Context, *UpdateSecretRequest) (*UpdateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecret not implemented")
}
func (UnimplementedSecretsServiceServer) DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedSecretsServiceServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedSecretsServiceServer) ResolveSecret(context.Context, *ResolveSecretRequest) (*ResolveSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSecret not implemented")
}
func (UnimplementedSecretsServiceServer) ResolveSecretExists(context.Context, *ResolveSecretExistsRequest) (*ResolveSecretExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSecretExists not implemented")
}
func (UnimplementedSecretsServiceServer) CreateImagePullSecret(context.Context, *CreateImagePullSecretRequest) (*CreateImagePullSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateImagePullSecret not implemented")
}
func (UnimplementedSecretsServiceServer) GetImagePullSecret(context.Context, *GetImagePullSecretRequest) (*GetImagePullSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImagePullSecret not implemented")
}
func (UnimplementedSecretsServiceServer) UpdateImagePullSecret(context.Context, *UpdateImagePullSecretRequest) (*UpdateImagePullSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateImagePullSecret not implemented")
}
func (UnimplementedSecretsServiceServer) DeleteImagePullSecret(context.Context, *DeleteImagePullSecretRequest) (*DeleteImagePullSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImagePullSecret not implemented")
}
func (UnimplementedSecretsServiceServer) ListImagePullSecrets(context.Context, *ListImagePullSecretsRequest) (*ListImagePullSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImagePullSecrets not implemented")
}
func (UnimplementedSecretsServiceServer) ResolveImagePullSecret(context.Context, *ResolveImagePullSecretRequest) (*ResolveImagePullSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveImagePullSecret not implemented")
}
func (UnimplementedSecretsServiceServer) testEmbeddedByValue() {}

// UnsafeSecretsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsServiceServer will
// result in compilation errors.
type UnsafeSecretsServiceServer interface {
	mustEmbedUnimplementedSecretsServiceServer()
}

func RegisterSecretsServiceServer(s grpc.ServiceRegistrar, srv SecretsServiceServer) {
	// If the following call panics, it indicates UnimplementedSecretsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretsService_ServiceDesc, srv)
}

func _SecretsService_CreateSecretProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).CreateSecretProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_CreateSecretProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).CreateSecretProvider(ctx, req.(*CreateSecretProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_GetSecretProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).GetSecretProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_GetSecretProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).GetSecretProvider(ctx, req.(*GetSecretProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_UpdateSecretProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).UpdateSecretProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_UpdateSecretProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).UpdateSecretProvider(ctx, req.(*UpdateSecretProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_DeleteSecretProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).DeleteSecretProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_DeleteSecretProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).DeleteSecretProvider(ctx, req.(*DeleteSecretProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ListSecretProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ListSecretProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ListSecretProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ListSecretProviders(ctx, req.(*ListSecretProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_UpdateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).UpdateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_UpdateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).UpdateSecret(ctx, req.(*UpdateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ResolveSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ResolveSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ResolveSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ResolveSecret(ctx, req.(*ResolveSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ResolveSecretExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSecretExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ResolveSecretExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ResolveSecretExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ResolveSecretExists(ctx, req.(*ResolveSecretExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_CreateImagePullSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImagePullSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).CreateImagePullSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_CreateImagePullSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).CreateImagePullSecret(ctx, req.(*CreateImagePullSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_GetImagePullSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImagePullSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).GetImagePullSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_GetImagePullSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).GetImagePullSecret(ctx, req.(*GetImagePullSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_UpdateImagePullSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateImagePullSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).UpdateImagePullSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_UpdateImagePullSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).UpdateImagePullSecret(ctx, req.(*UpdateImagePullSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_DeleteImagePullSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImagePullSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).DeleteImagePullSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_DeleteImagePullSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).DeleteImagePullSecret(ctx, req.(*DeleteImagePullSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ListImagePullSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagePullSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ListImagePullSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ListImagePullSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ListImagePullSecrets(ctx, req.(*ListImagePullSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ResolveImagePullSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveImagePullSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ResolveImagePullSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ResolveImagePullSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ResolveImagePullSecret(ctx, req.(*ResolveImagePullSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretsService_ServiceDesc is the grpc.ServiceDesc for SecretsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.secrets.v1.SecretsService",
	HandlerType: (*SecretsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSecretProvider",
			Handler:    _SecretsService_CreateSecretProvider_Handler,
		},
		{
			MethodName: "GetSecretProvider",
			Handler:    _SecretsService_GetSecretProvider_Handler,
		},
		{
			MethodName: "UpdateSecretProvider",
			Handler:    _SecretsService_UpdateSecretProvider_Handler,
		},
		{
			MethodName: "DeleteSecretProvider",
			Handler:    _SecretsService_DeleteSecretProvider_Handler,
		},
		{
			MethodName: "ListSecretProviders",
			Handler:    _SecretsService_ListSecretProviders_Handler,
		},
		{
			MethodName: "CreateSecret",
			Handler:    _SecretsService_CreateSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _SecretsService_GetSecret_Handler,
		},
		{
			MethodName: "UpdateSecret",
			Handler:    _SecretsService_UpdateSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _SecretsService_DeleteSecret_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _SecretsService_ListSecrets_Handler,
		},
		{
			MethodName: "ResolveSecret",
			Handler:    _SecretsService_ResolveSecret_Handler,
		},
		{
			MethodName: "ResolveSecretExists",
			Handler:    _SecretsService_ResolveSecretExists_Handler,
		},
		{
			MethodName: "CreateImagePullSecret",
			Handler:    _SecretsService_CreateImagePullSecret_Handler,
		},
		{
			MethodName: "GetImagePullSecret",
			Handler:    _SecretsService_GetImagePullSecret_Handler,
		},
		{
			MethodName: "UpdateImagePullSecret",
			Handler:    _SecretsService_UpdateImagePullSecret_Handler,
		},
		{
			MethodName: "DeleteImagePullSecret",
			Handler:    _SecretsService_DeleteImagePullSecret_Handler,
		},
		{
			MethodName: "ListImagePullSecrets",
			Handler:    _SecretsService_ListImagePullSecrets_Handler,
		},
		{
			MethodName: "ResolveImagePullSecret",
			Handler:    _SecretsService_ResolveImagePullSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/secrets/v1/secrets.proto",
}
